package constant

var OpenStateConst *OpenState

type OpenState struct {
	OPEN_STATE_NONE                                    uint16
	OPEN_STATE_PAIMON                                  uint16
	OPEN_STATE_PAIMON_NAVIGATION                       uint16
	OPEN_STATE_AVATAR_PROMOTE                          uint16
	OPEN_STATE_AVATAR_TALENT                           uint16
	OPEN_STATE_WEAPON_PROMOTE                          uint16
	OPEN_STATE_WEAPON_AWAKEN                           uint16
	OPEN_STATE_QUEST_REMIND                            uint16
	OPEN_STATE_GAME_GUIDE                              uint16
	OPEN_STATE_COOK                                    uint16
	OPEN_STATE_WEAPON_UPGRADE                          uint16
	OPEN_STATE_RELIQUARY_UPGRADE                       uint16
	OPEN_STATE_RELIQUARY_PROMOTE                       uint16
	OPEN_STATE_WEAPON_PROMOTE_GUIDE                    uint16
	OPEN_STATE_WEAPON_CHANGE_GUIDE                     uint16
	OPEN_STATE_PLAYER_LVUP_GUIDE                       uint16
	OPEN_STATE_FRESHMAN_GUIDE                          uint16
	OPEN_STATE_SKIP_FRESHMAN_GUIDE                     uint16
	OPEN_STATE_GUIDE_MOVE_CAMERA                       uint16
	OPEN_STATE_GUIDE_SCALE_CAMERA                      uint16
	OPEN_STATE_GUIDE_KEYBOARD                          uint16
	OPEN_STATE_GUIDE_MOVE                              uint16
	OPEN_STATE_GUIDE_JUMP                              uint16
	OPEN_STATE_GUIDE_SPRINT                            uint16
	OPEN_STATE_GUIDE_MAP                               uint16
	OPEN_STATE_GUIDE_ATTACK                            uint16
	OPEN_STATE_GUIDE_FLY                               uint16
	OPEN_STATE_GUIDE_TALENT                            uint16
	OPEN_STATE_GUIDE_RELIC                             uint16
	OPEN_STATE_GUIDE_RELIC_PROM                        uint16
	OPEN_STATE_COMBINE                                 uint16
	OPEN_STATE_GACHA                                   uint16
	OPEN_STATE_GUIDE_GACHA                             uint16
	OPEN_STATE_GUIDE_TEAM                              uint16
	OPEN_STATE_GUIDE_PROUD                             uint16
	OPEN_STATE_GUIDE_AVATAR_PROMOTE                    uint16
	OPEN_STATE_GUIDE_ADVENTURE_CARD                    uint16
	OPEN_STATE_FORGE                                   uint16
	OPEN_STATE_GUIDE_BAG                               uint16
	OPEN_STATE_EXPEDITION                              uint16
	OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK               uint16
	OPEN_STATE_GUIDE_ADVENTURE_DUNGEON                 uint16
	OPEN_STATE_TOWER                                   uint16
	OPEN_STATE_WORLD_STAMINA                           uint16
	OPEN_STATE_TOWER_FIRST_ENTER                       uint16
	OPEN_STATE_RESIN                                   uint16
	OPEN_STATE_LIMIT_REGION_FRESHMEAT                  uint16
	OPEN_STATE_LIMIT_REGION_GLOBAL                     uint16
	OPEN_STATE_MULTIPLAYER                             uint16
	OPEN_STATE_GUIDE_MOUSEPC                           uint16
	OPEN_STATE_GUIDE_MULTIPLAYER                       uint16
	OPEN_STATE_GUIDE_DUNGEONREWARD                     uint16
	OPEN_STATE_GUIDE_BLOSSOM                           uint16
	OPEN_STATE_AVATAR_FASHION                          uint16
	OPEN_STATE_PHOTOGRAPH                              uint16
	OPEN_STATE_GUIDE_KSLQUEST                          uint16
	OPEN_STATE_PERSONAL_LINE                           uint16
	OPEN_STATE_GUIDE_PERSONAL_LINE                     uint16
	OPEN_STATE_GUIDE_APPEARANCE                        uint16
	OPEN_STATE_GUIDE_PROCESS                           uint16
	OPEN_STATE_GUIDE_PERSONAL_LINE_KEY                 uint16
	OPEN_STATE_GUIDE_WIDGET                            uint16
	OPEN_STATE_GUIDE_ACTIVITY_SKILL_ASTER              uint16
	OPEN_STATE_GUIDE_COLDCLIMATE                       uint16
	OPEN_STATE_DERIVATIVE_MALL                         uint16
	OPEN_STATE_GUIDE_EXITMULTIPLAYER                   uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_BUILD           uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_REBUILD         uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_CARD            uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_MONSTER         uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_MISSION_CHECK   uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_BUILD_SELECT    uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_CHALLENGE_START uint16
	OPEN_STATE_GUIDE_CONVERT                           uint16
	OPEN_STATE_GUIDE_THEATREMACHANICUS_MULTIPLAYER     uint16
	OPEN_STATE_GUIDE_COOP_TASK                         uint16
	OPEN_STATE_GUIDE_HOMEWORLD_ADEPTIABODE             uint16
	OPEN_STATE_GUIDE_HOMEWORLD_DEPLOY                  uint16
	OPEN_STATE_GUIDE_CHANNELLERSLAB_EQUIP              uint16
	OPEN_STATE_GUIDE_CHANNELLERSLAB_MP_SOLUTION        uint16
	OPEN_STATE_GUIDE_CHANNELLERSLAB_POWER              uint16
	OPEN_STATE_GUIDE_HIDEANDSEEK_SKILL                 uint16
	OPEN_STATE_GUIDE_HOMEWORLD_MAPLIST                 uint16
	OPEN_STATE_GUIDE_RELICRESOLVE                      uint16
	OPEN_STATE_GUIDE_GGUIDE                            uint16
	OPEN_STATE_GUIDE_GGUIDE_HINT                       uint16
	OPEN_STATE_CITY_REPUATION_MENGDE                   uint16
	OPEN_STATE_CITY_REPUATION_LIYUE                    uint16
	OPEN_STATE_CITY_REPUATION_UI_HINT                  uint16
	OPEN_STATE_CITY_REPUATION_INAZUMA                  uint16
	OPEN_STATE_SHOP_TYPE_MALL                          uint16
	OPEN_STATE_SHOP_TYPE_RECOMMANDED                   uint16
	OPEN_STATE_SHOP_TYPE_GENESISCRYSTAL                uint16
	OPEN_STATE_SHOP_TYPE_GIFTPACKAGE                   uint16
	OPEN_STATE_SHOP_TYPE_PAIMON                        uint16
	OPEN_STATE_SHOP_TYPE_CITY                          uint16
	OPEN_STATE_SHOP_TYPE_BLACKSMITH                    uint16
	OPEN_STATE_SHOP_TYPE_GROCERY                       uint16
	OPEN_STATE_SHOP_TYPE_FOOD                          uint16
	OPEN_STATE_SHOP_TYPE_SEA_LAMP                      uint16
	OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP                  uint16
	OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY                 uint16
	OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR                uint16
	OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT              uint16
	OPEN_STATE_SHOP_TYPE_INAZUMA_SOUVENIR              uint16
	OPEN_STATE_SHOP_TYPE_NPC_TOMOKI                    uint16
	OPEN_ADVENTURE_MANUAL                              uint16
	OPEN_ADVENTURE_MANUAL_CITY_MENGDE                  uint16
	OPEN_ADVENTURE_MANUAL_CITY_LIYUE                   uint16
	OPEN_ADVENTURE_MANUAL_MONSTER                      uint16
	OPEN_ADVENTURE_MANUAL_BOSS_DUNGEON                 uint16
	OPEN_STATE_ACTIVITY_SEALAMP                        uint16
	OPEN_STATE_ACTIVITY_SEALAMP_TAB2                   uint16
	OPEN_STATE_ACTIVITY_SEALAMP_TAB3                   uint16
	OPEN_STATE_BATTLE_PASS                             uint16
	OPEN_STATE_BATTLE_PASS_ENTRY                       uint16
	OPEN_STATE_ACTIVITY_CRUCIBLE                       uint16
	OPEN_STATE_ACTIVITY_NEWBEEBOUNS_OPEN               uint16
	OPEN_STATE_ACTIVITY_NEWBEEBOUNS_CLOSE              uint16
	OPEN_STATE_ACTIVITY_ENTRY_OPEN                     uint16
	OPEN_STATE_MENGDE_INFUSEDCRYSTAL                   uint16
	OPEN_STATE_LIYUE_INFUSEDCRYSTAL                    uint16
	OPEN_STATE_SNOW_MOUNTAIN_ELDER_TREE                uint16
	OPEN_STATE_MIRACLE_RING                            uint16
	OPEN_STATE_COOP_LINE                               uint16
	OPEN_STATE_INAZUMA_INFUSEDCRYSTAL                  uint16
	OPEN_STATE_FISH                                    uint16
	OPEN_STATE_GUIDE_SUMO_TEAM_SKILL                   uint16
	OPEN_STATE_GUIDE_FISH_RECIPE                       uint16
	OPEN_STATE_HOME                                    uint16
	OPEN_STATE_ACTIVITY_HOMEWORLD                      uint16
	OPEN_STATE_ADEPTIABODE                             uint16
	OPEN_STATE_HOME_AVATAR                             uint16
	OPEN_STATE_HOME_EDIT                               uint16
	OPEN_STATE_HOME_EDIT_TIPS                          uint16
	OPEN_STATE_RELIQUARY_DECOMPOSE                     uint16
	OPEN_STATE_ACTIVITY_H5                             uint16
	OPEN_STATE_ORAIONOKAMI                             uint16
	OPEN_STATE_GUIDE_CHESS_MISSION_CHECK               uint16
	OPEN_STATE_GUIDE_CHESS_BUILD                       uint16
	OPEN_STATE_GUIDE_CHESS_WIND_TOWER_CIRCLE           uint16
	OPEN_STATE_GUIDE_CHESS_CARD_SELECT                 uint16
	OPEN_STATE_INAZUMA_MAINQUEST_FINISHED              uint16
	OPEN_STATE_PAIMON_LVINFO                           uint16
	OPEN_STATE_TELEPORT_HUD                            uint16
	OPEN_STATE_GUIDE_MAP_UNLOCK                        uint16
	OPEN_STATE_GUIDE_PAIMON_LVINFO                     uint16
	OPEN_STATE_GUIDE_AMBORTRANSPORT                    uint16
	OPEN_STATE_GUIDE_FLY_SECOND                        uint16
	OPEN_STATE_GUIDE_KAEYA_CLUE                        uint16
	OPEN_STATE_CAPTURE_CODEX                           uint16
	OPEN_STATE_ACTIVITY_FISH_OPEN                      uint16
	OPEN_STATE_ACTIVITY_FISH_CLOSE                     uint16
	OPEN_STATE_GUIDE_ROGUE_MAP                         uint16
	OPEN_STATE_GUIDE_ROGUE_RUNE                        uint16
	OPEN_STATE_GUIDE_BARTENDER_FORMULA                 uint16
	OPEN_STATE_GUIDE_BARTENDER_MIX                     uint16
	OPEN_STATE_GUIDE_BARTENDER_CUP                     uint16
	OPEN_STATE_GUIDE_MAIL_FAVORITES                    uint16
	OPEN_STATE_GUIDE_POTION_CONFIGURE                  uint16
	OPEN_STATE_GUIDE_LANV2_FIREWORK                    uint16
	OPEN_STATE_LOADINGTIPS_ENKANOMIYA                  uint16
	OPEN_STATE_MICHIAE_CASKET                          uint16
	OPEN_STATE_MAIL_COLLECT_UNLOCK_RED_POINT           uint16
	OPEN_STATE_LUMEN_STONE                             uint16
	OPEN_STATE_GUIDE_CRYSTALLINK_BUFF                  uint16
}

func InitOpenStateConst() {
	OpenStateConst = new(OpenState)

	OpenStateConst.OPEN_STATE_NONE = 0
	OpenStateConst.OPEN_STATE_PAIMON = 1
	OpenStateConst.OPEN_STATE_PAIMON_NAVIGATION = 2
	OpenStateConst.OPEN_STATE_AVATAR_PROMOTE = 3
	OpenStateConst.OPEN_STATE_AVATAR_TALENT = 4
	OpenStateConst.OPEN_STATE_WEAPON_PROMOTE = 5
	OpenStateConst.OPEN_STATE_WEAPON_AWAKEN = 6
	OpenStateConst.OPEN_STATE_QUEST_REMIND = 7
	OpenStateConst.OPEN_STATE_GAME_GUIDE = 8
	OpenStateConst.OPEN_STATE_COOK = 9
	OpenStateConst.OPEN_STATE_WEAPON_UPGRADE = 10
	OpenStateConst.OPEN_STATE_RELIQUARY_UPGRADE = 11
	OpenStateConst.OPEN_STATE_RELIQUARY_PROMOTE = 12
	OpenStateConst.OPEN_STATE_WEAPON_PROMOTE_GUIDE = 13
	OpenStateConst.OPEN_STATE_WEAPON_CHANGE_GUIDE = 14
	OpenStateConst.OPEN_STATE_PLAYER_LVUP_GUIDE = 15
	OpenStateConst.OPEN_STATE_FRESHMAN_GUIDE = 16
	OpenStateConst.OPEN_STATE_SKIP_FRESHMAN_GUIDE = 17
	OpenStateConst.OPEN_STATE_GUIDE_MOVE_CAMERA = 18
	OpenStateConst.OPEN_STATE_GUIDE_SCALE_CAMERA = 19
	OpenStateConst.OPEN_STATE_GUIDE_KEYBOARD = 20
	OpenStateConst.OPEN_STATE_GUIDE_MOVE = 21
	OpenStateConst.OPEN_STATE_GUIDE_JUMP = 22
	OpenStateConst.OPEN_STATE_GUIDE_SPRINT = 23
	OpenStateConst.OPEN_STATE_GUIDE_MAP = 24
	OpenStateConst.OPEN_STATE_GUIDE_ATTACK = 25
	OpenStateConst.OPEN_STATE_GUIDE_FLY = 26
	OpenStateConst.OPEN_STATE_GUIDE_TALENT = 27
	OpenStateConst.OPEN_STATE_GUIDE_RELIC = 28
	OpenStateConst.OPEN_STATE_GUIDE_RELIC_PROM = 29
	OpenStateConst.OPEN_STATE_COMBINE = 30
	OpenStateConst.OPEN_STATE_GACHA = 31
	OpenStateConst.OPEN_STATE_GUIDE_GACHA = 32
	OpenStateConst.OPEN_STATE_GUIDE_TEAM = 33
	OpenStateConst.OPEN_STATE_GUIDE_PROUD = 34
	OpenStateConst.OPEN_STATE_GUIDE_AVATAR_PROMOTE = 35
	OpenStateConst.OPEN_STATE_GUIDE_ADVENTURE_CARD = 36
	OpenStateConst.OPEN_STATE_FORGE = 37
	OpenStateConst.OPEN_STATE_GUIDE_BAG = 38
	OpenStateConst.OPEN_STATE_EXPEDITION = 39
	OpenStateConst.OPEN_STATE_GUIDE_ADVENTURE_DAILYTASK = 40
	OpenStateConst.OPEN_STATE_GUIDE_ADVENTURE_DUNGEON = 41
	OpenStateConst.OPEN_STATE_TOWER = 42
	OpenStateConst.OPEN_STATE_WORLD_STAMINA = 43
	OpenStateConst.OPEN_STATE_TOWER_FIRST_ENTER = 44
	OpenStateConst.OPEN_STATE_RESIN = 45
	OpenStateConst.OPEN_STATE_LIMIT_REGION_FRESHMEAT = 47
	OpenStateConst.OPEN_STATE_LIMIT_REGION_GLOBAL = 48
	OpenStateConst.OPEN_STATE_MULTIPLAYER = 49
	OpenStateConst.OPEN_STATE_GUIDE_MOUSEPC = 50
	OpenStateConst.OPEN_STATE_GUIDE_MULTIPLAYER = 51
	OpenStateConst.OPEN_STATE_GUIDE_DUNGEONREWARD = 52
	OpenStateConst.OPEN_STATE_GUIDE_BLOSSOM = 53
	OpenStateConst.OPEN_STATE_AVATAR_FASHION = 54
	OpenStateConst.OPEN_STATE_PHOTOGRAPH = 55
	OpenStateConst.OPEN_STATE_GUIDE_KSLQUEST = 56
	OpenStateConst.OPEN_STATE_PERSONAL_LINE = 57
	OpenStateConst.OPEN_STATE_GUIDE_PERSONAL_LINE = 58
	OpenStateConst.OPEN_STATE_GUIDE_APPEARANCE = 59
	OpenStateConst.OPEN_STATE_GUIDE_PROCESS = 60
	OpenStateConst.OPEN_STATE_GUIDE_PERSONAL_LINE_KEY = 61
	OpenStateConst.OPEN_STATE_GUIDE_WIDGET = 62
	OpenStateConst.OPEN_STATE_GUIDE_ACTIVITY_SKILL_ASTER = 63
	OpenStateConst.OPEN_STATE_GUIDE_COLDCLIMATE = 64
	OpenStateConst.OPEN_STATE_DERIVATIVE_MALL = 65
	OpenStateConst.OPEN_STATE_GUIDE_EXITMULTIPLAYER = 66
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_BUILD = 67
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_REBUILD = 68
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_CARD = 69
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_MONSTER = 70
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_MISSION_CHECK = 71
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_BUILD_SELECT = 72
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_CHALLENGE_START = 73
	OpenStateConst.OPEN_STATE_GUIDE_CONVERT = 74
	OpenStateConst.OPEN_STATE_GUIDE_THEATREMACHANICUS_MULTIPLAYER = 75
	OpenStateConst.OPEN_STATE_GUIDE_COOP_TASK = 76
	OpenStateConst.OPEN_STATE_GUIDE_HOMEWORLD_ADEPTIABODE = 77
	OpenStateConst.OPEN_STATE_GUIDE_HOMEWORLD_DEPLOY = 78
	OpenStateConst.OPEN_STATE_GUIDE_CHANNELLERSLAB_EQUIP = 79
	OpenStateConst.OPEN_STATE_GUIDE_CHANNELLERSLAB_MP_SOLUTION = 80
	OpenStateConst.OPEN_STATE_GUIDE_CHANNELLERSLAB_POWER = 81
	OpenStateConst.OPEN_STATE_GUIDE_HIDEANDSEEK_SKILL = 82
	OpenStateConst.OPEN_STATE_GUIDE_HOMEWORLD_MAPLIST = 83
	OpenStateConst.OPEN_STATE_GUIDE_RELICRESOLVE = 84
	OpenStateConst.OPEN_STATE_GUIDE_GGUIDE = 85
	OpenStateConst.OPEN_STATE_GUIDE_GGUIDE_HINT = 86
	OpenStateConst.OPEN_STATE_CITY_REPUATION_MENGDE = 800
	OpenStateConst.OPEN_STATE_CITY_REPUATION_LIYUE = 801
	OpenStateConst.OPEN_STATE_CITY_REPUATION_UI_HINT = 802
	OpenStateConst.OPEN_STATE_CITY_REPUATION_INAZUMA = 803
	OpenStateConst.OPEN_STATE_SHOP_TYPE_MALL = 900
	OpenStateConst.OPEN_STATE_SHOP_TYPE_RECOMMANDED = 901
	OpenStateConst.OPEN_STATE_SHOP_TYPE_GENESISCRYSTAL = 902
	OpenStateConst.OPEN_STATE_SHOP_TYPE_GIFTPACKAGE = 903
	OpenStateConst.OPEN_STATE_SHOP_TYPE_PAIMON = 1001
	OpenStateConst.OPEN_STATE_SHOP_TYPE_CITY = 1002
	OpenStateConst.OPEN_STATE_SHOP_TYPE_BLACKSMITH = 1003
	OpenStateConst.OPEN_STATE_SHOP_TYPE_GROCERY = 1004
	OpenStateConst.OPEN_STATE_SHOP_TYPE_FOOD = 1005
	OpenStateConst.OPEN_STATE_SHOP_TYPE_SEA_LAMP = 1006
	OpenStateConst.OPEN_STATE_SHOP_TYPE_VIRTUAL_SHOP = 1007
	OpenStateConst.OPEN_STATE_SHOP_TYPE_LIYUE_GROCERY = 1008
	OpenStateConst.OPEN_STATE_SHOP_TYPE_LIYUE_SOUVENIR = 1009
	OpenStateConst.OPEN_STATE_SHOP_TYPE_LIYUE_RESTAURANT = 1010
	OpenStateConst.OPEN_STATE_SHOP_TYPE_INAZUMA_SOUVENIR = 1011
	OpenStateConst.OPEN_STATE_SHOP_TYPE_NPC_TOMOKI = 1012
	OpenStateConst.OPEN_ADVENTURE_MANUAL = 1100
	OpenStateConst.OPEN_ADVENTURE_MANUAL_CITY_MENGDE = 1101
	OpenStateConst.OPEN_ADVENTURE_MANUAL_CITY_LIYUE = 1102
	OpenStateConst.OPEN_ADVENTURE_MANUAL_MONSTER = 1103
	OpenStateConst.OPEN_ADVENTURE_MANUAL_BOSS_DUNGEON = 1104
	OpenStateConst.OPEN_STATE_ACTIVITY_SEALAMP = 1200
	OpenStateConst.OPEN_STATE_ACTIVITY_SEALAMP_TAB2 = 1201
	OpenStateConst.OPEN_STATE_ACTIVITY_SEALAMP_TAB3 = 1202
	OpenStateConst.OPEN_STATE_BATTLE_PASS = 1300
	OpenStateConst.OPEN_STATE_BATTLE_PASS_ENTRY = 1301
	OpenStateConst.OPEN_STATE_ACTIVITY_CRUCIBLE = 1400
	OpenStateConst.OPEN_STATE_ACTIVITY_NEWBEEBOUNS_OPEN = 1401
	OpenStateConst.OPEN_STATE_ACTIVITY_NEWBEEBOUNS_CLOSE = 1402
	OpenStateConst.OPEN_STATE_ACTIVITY_ENTRY_OPEN = 1403
	OpenStateConst.OPEN_STATE_MENGDE_INFUSEDCRYSTAL = 1404
	OpenStateConst.OPEN_STATE_LIYUE_INFUSEDCRYSTAL = 1405
	OpenStateConst.OPEN_STATE_SNOW_MOUNTAIN_ELDER_TREE = 1406
	OpenStateConst.OPEN_STATE_MIRACLE_RING = 1407
	OpenStateConst.OPEN_STATE_COOP_LINE = 1408
	OpenStateConst.OPEN_STATE_INAZUMA_INFUSEDCRYSTAL = 1409
	OpenStateConst.OPEN_STATE_FISH = 1410
	OpenStateConst.OPEN_STATE_GUIDE_SUMO_TEAM_SKILL = 1411
	OpenStateConst.OPEN_STATE_GUIDE_FISH_RECIPE = 1412
	OpenStateConst.OPEN_STATE_HOME = 1500
	OpenStateConst.OPEN_STATE_ACTIVITY_HOMEWORLD = 1501
	OpenStateConst.OPEN_STATE_ADEPTIABODE = 1502
	OpenStateConst.OPEN_STATE_HOME_AVATAR = 1503
	OpenStateConst.OPEN_STATE_HOME_EDIT = 1504
	OpenStateConst.OPEN_STATE_HOME_EDIT_TIPS = 1505
	OpenStateConst.OPEN_STATE_RELIQUARY_DECOMPOSE = 1600
	OpenStateConst.OPEN_STATE_ACTIVITY_H5 = 1700
	OpenStateConst.OPEN_STATE_ORAIONOKAMI = 2000
	OpenStateConst.OPEN_STATE_GUIDE_CHESS_MISSION_CHECK = 2001
	OpenStateConst.OPEN_STATE_GUIDE_CHESS_BUILD = 2002
	OpenStateConst.OPEN_STATE_GUIDE_CHESS_WIND_TOWER_CIRCLE = 2003
	OpenStateConst.OPEN_STATE_GUIDE_CHESS_CARD_SELECT = 2004
	OpenStateConst.OPEN_STATE_INAZUMA_MAINQUEST_FINISHED = 2005
	OpenStateConst.OPEN_STATE_PAIMON_LVINFO = 2100
	OpenStateConst.OPEN_STATE_TELEPORT_HUD = 2101
	OpenStateConst.OPEN_STATE_GUIDE_MAP_UNLOCK = 2102
	OpenStateConst.OPEN_STATE_GUIDE_PAIMON_LVINFO = 2103
	OpenStateConst.OPEN_STATE_GUIDE_AMBORTRANSPORT = 2104
	OpenStateConst.OPEN_STATE_GUIDE_FLY_SECOND = 2105
	OpenStateConst.OPEN_STATE_GUIDE_KAEYA_CLUE = 2106
	OpenStateConst.OPEN_STATE_CAPTURE_CODEX = 2107
	OpenStateConst.OPEN_STATE_ACTIVITY_FISH_OPEN = 2200
	OpenStateConst.OPEN_STATE_ACTIVITY_FISH_CLOSE = 2201
	OpenStateConst.OPEN_STATE_GUIDE_ROGUE_MAP = 2205
	OpenStateConst.OPEN_STATE_GUIDE_ROGUE_RUNE = 2206
	OpenStateConst.OPEN_STATE_GUIDE_BARTENDER_FORMULA = 2210
	OpenStateConst.OPEN_STATE_GUIDE_BARTENDER_MIX = 2211
	OpenStateConst.OPEN_STATE_GUIDE_BARTENDER_CUP = 2212
	OpenStateConst.OPEN_STATE_GUIDE_MAIL_FAVORITES = 2400
	OpenStateConst.OPEN_STATE_GUIDE_POTION_CONFIGURE = 2401
	OpenStateConst.OPEN_STATE_GUIDE_LANV2_FIREWORK = 2402
	OpenStateConst.OPEN_STATE_LOADINGTIPS_ENKANOMIYA = 2403
	OpenStateConst.OPEN_STATE_MICHIAE_CASKET = 2500
	OpenStateConst.OPEN_STATE_MAIL_COLLECT_UNLOCK_RED_POINT = 2501
	OpenStateConst.OPEN_STATE_LUMEN_STONE = 2600
	OpenStateConst.OPEN_STATE_GUIDE_CRYSTALLINK_BUFF = 2601
}
