// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: ChannelerSlabLoopDungeonInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelerSlabLoopDungeonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score                  uint32   `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	DungeonIndex           uint32   `protobuf:"varint,4,opt,name=dungeon_index,json=dungeonIndex,proto3" json:"dungeon_index,omitempty"`
	OpenTime               uint32   `protobuf:"varint,12,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	IsFirstPassRewardTaken bool     `protobuf:"varint,9,opt,name=is_first_pass_reward_taken,json=isFirstPassRewardTaken,proto3" json:"is_first_pass_reward_taken,omitempty"`
	LastConditionIdList    []uint32 `protobuf:"varint,14,rep,packed,name=last_condition_id_list,json=lastConditionIdList,proto3" json:"last_condition_id_list,omitempty"`
	IsOpen                 bool     `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
}

func (x *ChannelerSlabLoopDungeonInfo) Reset() {
	*x = ChannelerSlabLoopDungeonInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChannelerSlabLoopDungeonInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelerSlabLoopDungeonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelerSlabLoopDungeonInfo) ProtoMessage() {}

func (x *ChannelerSlabLoopDungeonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ChannelerSlabLoopDungeonInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelerSlabLoopDungeonInfo.ProtoReflect.Descriptor instead.
func (*ChannelerSlabLoopDungeonInfo) Descriptor() ([]byte, []int) {
	return file_ChannelerSlabLoopDungeonInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelerSlabLoopDungeonInfo) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ChannelerSlabLoopDungeonInfo) GetDungeonIndex() uint32 {
	if x != nil {
		return x.DungeonIndex
	}
	return 0
}

func (x *ChannelerSlabLoopDungeonInfo) GetOpenTime() uint32 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *ChannelerSlabLoopDungeonInfo) GetIsFirstPassRewardTaken() bool {
	if x != nil {
		return x.IsFirstPassRewardTaken
	}
	return false
}

func (x *ChannelerSlabLoopDungeonInfo) GetLastConditionIdList() []uint32 {
	if x != nil {
		return x.LastConditionIdList
	}
	return nil
}

func (x *ChannelerSlabLoopDungeonInfo) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

var File_ChannelerSlabLoopDungeonInfo_proto protoreflect.FileDescriptor

var file_ChannelerSlabLoopDungeonInfo_proto_rawDesc = []byte{
	0x0a, 0x22, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x62, 0x4c,
	0x6f, 0x6f, 0x70, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02, 0x0a, 0x1c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x65, 0x72, 0x53, 0x6c, 0x61, 0x62, 0x4c, 0x6f, 0x6f, 0x70, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a,
	0x1a, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x61, 0x6b, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x16, 0x69, 0x73, 0x46, 0x69, 0x72, 0x73, 0x74, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x54, 0x61, 0x6b, 0x65, 0x6e, 0x12, 0x33, 0x0a, 0x16, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x13, 0x6c, 0x61, 0x73, 0x74, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ChannelerSlabLoopDungeonInfo_proto_rawDescOnce sync.Once
	file_ChannelerSlabLoopDungeonInfo_proto_rawDescData = file_ChannelerSlabLoopDungeonInfo_proto_rawDesc
)

func file_ChannelerSlabLoopDungeonInfo_proto_rawDescGZIP() []byte {
	file_ChannelerSlabLoopDungeonInfo_proto_rawDescOnce.Do(func() {
		file_ChannelerSlabLoopDungeonInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChannelerSlabLoopDungeonInfo_proto_rawDescData)
	})
	return file_ChannelerSlabLoopDungeonInfo_proto_rawDescData
}

var file_ChannelerSlabLoopDungeonInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ChannelerSlabLoopDungeonInfo_proto_goTypes = []interface{}{
	(*ChannelerSlabLoopDungeonInfo)(nil), // 0: ChannelerSlabLoopDungeonInfo
}
var file_ChannelerSlabLoopDungeonInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ChannelerSlabLoopDungeonInfo_proto_init() }
func file_ChannelerSlabLoopDungeonInfo_proto_init() {
	if File_ChannelerSlabLoopDungeonInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ChannelerSlabLoopDungeonInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelerSlabLoopDungeonInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChannelerSlabLoopDungeonInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChannelerSlabLoopDungeonInfo_proto_goTypes,
		DependencyIndexes: file_ChannelerSlabLoopDungeonInfo_proto_depIdxs,
		MessageInfos:      file_ChannelerSlabLoopDungeonInfo_proto_msgTypes,
	}.Build()
	File_ChannelerSlabLoopDungeonInfo_proto = out.File
	file_ChannelerSlabLoopDungeonInfo_proto_rawDesc = nil
	file_ChannelerSlabLoopDungeonInfo_proto_goTypes = nil
	file_ChannelerSlabLoopDungeonInfo_proto_depIdxs = nil
}
