// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: LunaRiteAreaInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LunaRiteAreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SacrificeList       []uint32               `protobuf:"varint,11,rep,packed,name=sacrifice_list,json=sacrificeList,proto3" json:"sacrifice_list,omitempty"`
	HintStatus          LunaRiteHintStatusType `protobuf:"varint,7,opt,name=hint_status,json=hintStatus,proto3,enum=LunaRiteHintStatusType" json:"hint_status,omitempty"`
	SacrificeRewardList []uint32               `protobuf:"varint,4,rep,packed,name=sacrifice_reward_list,json=sacrificeRewardList,proto3" json:"sacrifice_reward_list,omitempty"`
	AreaId              uint32                 `protobuf:"varint,8,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	ChallengeIndex      uint32                 `protobuf:"varint,6,opt,name=challenge_index,json=challengeIndex,proto3" json:"challenge_index,omitempty"`
}

func (x *LunaRiteAreaInfo) Reset() {
	*x = LunaRiteAreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LunaRiteAreaInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LunaRiteAreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunaRiteAreaInfo) ProtoMessage() {}

func (x *LunaRiteAreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_LunaRiteAreaInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunaRiteAreaInfo.ProtoReflect.Descriptor instead.
func (*LunaRiteAreaInfo) Descriptor() ([]byte, []int) {
	return file_LunaRiteAreaInfo_proto_rawDescGZIP(), []int{0}
}

func (x *LunaRiteAreaInfo) GetSacrificeList() []uint32 {
	if x != nil {
		return x.SacrificeList
	}
	return nil
}

func (x *LunaRiteAreaInfo) GetHintStatus() LunaRiteHintStatusType {
	if x != nil {
		return x.HintStatus
	}
	return LunaRiteHintStatusType_LUNA_RITE_HINT_STATUS_TYPE_DEFAULT
}

func (x *LunaRiteAreaInfo) GetSacrificeRewardList() []uint32 {
	if x != nil {
		return x.SacrificeRewardList
	}
	return nil
}

func (x *LunaRiteAreaInfo) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *LunaRiteAreaInfo) GetChallengeIndex() uint32 {
	if x != nil {
		return x.ChallengeIndex
	}
	return 0
}

var File_LunaRiteAreaInfo_proto protoreflect.FileDescriptor

var file_LunaRiteAreaInfo_proto_rawDesc = []byte{
	0x0a, 0x16, 0x4c, 0x75, 0x6e, 0x61, 0x52, 0x69, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x4c, 0x75, 0x6e, 0x61, 0x52, 0x69,
	0x74, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe9, 0x01, 0x0a, 0x10, 0x4c, 0x75, 0x6e, 0x61, 0x52,
	0x69, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x61, 0x63, 0x72, 0x69, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x61, 0x63, 0x72, 0x69, 0x66, 0x69, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x68, 0x69, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4c, 0x75, 0x6e, 0x61, 0x52, 0x69,
	0x74, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x68, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x15,
	0x73, 0x61, 0x63, 0x72, 0x69, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x13, 0x73, 0x61, 0x63,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LunaRiteAreaInfo_proto_rawDescOnce sync.Once
	file_LunaRiteAreaInfo_proto_rawDescData = file_LunaRiteAreaInfo_proto_rawDesc
)

func file_LunaRiteAreaInfo_proto_rawDescGZIP() []byte {
	file_LunaRiteAreaInfo_proto_rawDescOnce.Do(func() {
		file_LunaRiteAreaInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_LunaRiteAreaInfo_proto_rawDescData)
	})
	return file_LunaRiteAreaInfo_proto_rawDescData
}

var file_LunaRiteAreaInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_LunaRiteAreaInfo_proto_goTypes = []interface{}{
	(*LunaRiteAreaInfo)(nil),    // 0: LunaRiteAreaInfo
	(LunaRiteHintStatusType)(0), // 1: LunaRiteHintStatusType
}
var file_LunaRiteAreaInfo_proto_depIdxs = []int32{
	1, // 0: LunaRiteAreaInfo.hint_status:type_name -> LunaRiteHintStatusType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_LunaRiteAreaInfo_proto_init() }
func file_LunaRiteAreaInfo_proto_init() {
	if File_LunaRiteAreaInfo_proto != nil {
		return
	}
	file_LunaRiteHintStatusType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_LunaRiteAreaInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LunaRiteAreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LunaRiteAreaInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_LunaRiteAreaInfo_proto_goTypes,
		DependencyIndexes: file_LunaRiteAreaInfo_proto_depIdxs,
		MessageInfos:      file_LunaRiteAreaInfo_proto_msgTypes,
	}.Build()
	File_LunaRiteAreaInfo_proto = out.File
	file_LunaRiteAreaInfo_proto_rawDesc = nil
	file_LunaRiteAreaInfo_proto_goTypes = nil
	file_LunaRiteAreaInfo_proto_depIdxs = nil
}
