// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SceneGalleryIslandPartyRaftInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneGalleryIslandPartyRaftInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin                uint32              `protobuf:"varint,6,opt,name=coin,proto3" json:"coin,omitempty"`
	Unk2800_ENJGEFBCLOL Unk2800_FMAOEPEBKHB `protobuf:"varint,7,opt,name=Unk2800_ENJGEFBCLOL,json=Unk2800ENJGEFBCLOL,proto3,enum=Unk2800_FMAOEPEBKHB" json:"Unk2800_ENJGEFBCLOL,omitempty"`
	Unk2800_BAEEDEAADIA uint32              `protobuf:"varint,1,opt,name=Unk2800_BAEEDEAADIA,json=Unk2800BAEEDEAADIA,proto3" json:"Unk2800_BAEEDEAADIA,omitempty"`
	Unk2800_EOFOECJJMLJ uint32              `protobuf:"varint,15,opt,name=Unk2800_EOFOECJJMLJ,json=Unk2800EOFOECJJMLJ,proto3" json:"Unk2800_EOFOECJJMLJ,omitempty"`
	PointId             uint32              `protobuf:"varint,12,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	Unk2800_MKNGANDAJFJ uint32              `protobuf:"varint,4,opt,name=Unk2800_MKNGANDAJFJ,json=Unk2800MKNGANDAJFJ,proto3" json:"Unk2800_MKNGANDAJFJ,omitempty"`
}

func (x *SceneGalleryIslandPartyRaftInfo) Reset() {
	*x = SceneGalleryIslandPartyRaftInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneGalleryIslandPartyRaftInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneGalleryIslandPartyRaftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneGalleryIslandPartyRaftInfo) ProtoMessage() {}

func (x *SceneGalleryIslandPartyRaftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SceneGalleryIslandPartyRaftInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneGalleryIslandPartyRaftInfo.ProtoReflect.Descriptor instead.
func (*SceneGalleryIslandPartyRaftInfo) Descriptor() ([]byte, []int) {
	return file_SceneGalleryIslandPartyRaftInfo_proto_rawDescGZIP(), []int{0}
}

func (x *SceneGalleryIslandPartyRaftInfo) GetCoin() uint32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *SceneGalleryIslandPartyRaftInfo) GetUnk2800_ENJGEFBCLOL() Unk2800_FMAOEPEBKHB {
	if x != nil {
		return x.Unk2800_ENJGEFBCLOL
	}
	return Unk2800_FMAOEPEBKHB_Unk2800_FMAOEPEBKHB_Unk2800_IBMPPHFLKEO
}

func (x *SceneGalleryIslandPartyRaftInfo) GetUnk2800_BAEEDEAADIA() uint32 {
	if x != nil {
		return x.Unk2800_BAEEDEAADIA
	}
	return 0
}

func (x *SceneGalleryIslandPartyRaftInfo) GetUnk2800_EOFOECJJMLJ() uint32 {
	if x != nil {
		return x.Unk2800_EOFOECJJMLJ
	}
	return 0
}

func (x *SceneGalleryIslandPartyRaftInfo) GetPointId() uint32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *SceneGalleryIslandPartyRaftInfo) GetUnk2800_MKNGANDAJFJ() uint32 {
	if x != nil {
		return x.Unk2800_MKNGANDAJFJ
	}
	return 0
}

var File_SceneGalleryIslandPartyRaftInfo_proto protoreflect.FileDescriptor

var file_SceneGalleryIslandPartyRaftInfo_proto_rawDesc = []byte{
	0x0a, 0x25, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x49, 0x73,
	0x6c, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x61, 0x66, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30,
	0x5f, 0x46, 0x4d, 0x41, 0x4f, 0x45, 0x50, 0x45, 0x42, 0x4b, 0x48, 0x42, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xaa, 0x02, 0x0a, 0x1f, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x47, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x79, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x61,
	0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x45, 0x0a, 0x13, 0x55, 0x6e,
	0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x45, 0x4e, 0x4a, 0x47, 0x45, 0x46, 0x42, 0x43, 0x4c, 0x4f,
	0x4c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30,
	0x30, 0x5f, 0x46, 0x4d, 0x41, 0x4f, 0x45, 0x50, 0x45, 0x42, 0x4b, 0x48, 0x42, 0x52, 0x12, 0x55,
	0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x45, 0x4e, 0x4a, 0x47, 0x45, 0x46, 0x42, 0x43, 0x4c, 0x4f,
	0x4c, 0x12, 0x2f, 0x0a, 0x13, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x42, 0x41, 0x45,
	0x45, 0x44, 0x45, 0x41, 0x41, 0x44, 0x49, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12,
	0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x42, 0x41, 0x45, 0x45, 0x44, 0x45, 0x41, 0x41, 0x44,
	0x49, 0x41, 0x12, 0x2f, 0x0a, 0x13, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x45, 0x4f,
	0x46, 0x4f, 0x45, 0x43, 0x4a, 0x4a, 0x4d, 0x4c, 0x4a, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x12, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x45, 0x4f, 0x46, 0x4f, 0x45, 0x43, 0x4a, 0x4a,
	0x4d, 0x4c, 0x4a, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2f,
	0x0a, 0x13, 0x55, 0x6e, 0x6b, 0x32, 0x38, 0x30, 0x30, 0x5f, 0x4d, 0x4b, 0x4e, 0x47, 0x41, 0x4e,
	0x44, 0x41, 0x4a, 0x46, 0x4a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x55, 0x6e, 0x6b,
	0x32, 0x38, 0x30, 0x30, 0x4d, 0x4b, 0x4e, 0x47, 0x41, 0x4e, 0x44, 0x41, 0x4a, 0x46, 0x4a, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_SceneGalleryIslandPartyRaftInfo_proto_rawDescOnce sync.Once
	file_SceneGalleryIslandPartyRaftInfo_proto_rawDescData = file_SceneGalleryIslandPartyRaftInfo_proto_rawDesc
)

func file_SceneGalleryIslandPartyRaftInfo_proto_rawDescGZIP() []byte {
	file_SceneGalleryIslandPartyRaftInfo_proto_rawDescOnce.Do(func() {
		file_SceneGalleryIslandPartyRaftInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneGalleryIslandPartyRaftInfo_proto_rawDescData)
	})
	return file_SceneGalleryIslandPartyRaftInfo_proto_rawDescData
}

var file_SceneGalleryIslandPartyRaftInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneGalleryIslandPartyRaftInfo_proto_goTypes = []interface{}{
	(*SceneGalleryIslandPartyRaftInfo)(nil), // 0: SceneGalleryIslandPartyRaftInfo
	(Unk2800_FMAOEPEBKHB)(0),                // 1: Unk2800_FMAOEPEBKHB
}
var file_SceneGalleryIslandPartyRaftInfo_proto_depIdxs = []int32{
	1, // 0: SceneGalleryIslandPartyRaftInfo.Unk2800_ENJGEFBCLOL:type_name -> Unk2800_FMAOEPEBKHB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SceneGalleryIslandPartyRaftInfo_proto_init() }
func file_SceneGalleryIslandPartyRaftInfo_proto_init() {
	if File_SceneGalleryIslandPartyRaftInfo_proto != nil {
		return
	}
	file_Unk2800_FMAOEPEBKHB_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SceneGalleryIslandPartyRaftInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneGalleryIslandPartyRaftInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneGalleryIslandPartyRaftInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneGalleryIslandPartyRaftInfo_proto_goTypes,
		DependencyIndexes: file_SceneGalleryIslandPartyRaftInfo_proto_depIdxs,
		MessageInfos:      file_SceneGalleryIslandPartyRaftInfo_proto_msgTypes,
	}.Build()
	File_SceneGalleryIslandPartyRaftInfo_proto = out.File
	file_SceneGalleryIslandPartyRaftInfo_proto_rawDesc = nil
	file_SceneGalleryIslandPartyRaftInfo_proto_goTypes = nil
	file_SceneGalleryIslandPartyRaftInfo_proto_depIdxs = nil
}
