// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SealBattleProgressNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 232
// EnetChannelId: 0
// EnetIsReliable: true
type SealBattleProgressNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SealEntityId uint32 `protobuf:"varint,9,opt,name=seal_entity_id,json=sealEntityId,proto3" json:"seal_entity_id,omitempty"`
	MaxProgress  uint32 `protobuf:"varint,10,opt,name=max_progress,json=maxProgress,proto3" json:"max_progress,omitempty"`
	SealRadius   uint32 `protobuf:"varint,4,opt,name=seal_radius,json=sealRadius,proto3" json:"seal_radius,omitempty"`
	Progress     uint32 `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	EndTime      uint32 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *SealBattleProgressNotify) Reset() {
	*x = SealBattleProgressNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SealBattleProgressNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SealBattleProgressNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealBattleProgressNotify) ProtoMessage() {}

func (x *SealBattleProgressNotify) ProtoReflect() protoreflect.Message {
	mi := &file_SealBattleProgressNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealBattleProgressNotify.ProtoReflect.Descriptor instead.
func (*SealBattleProgressNotify) Descriptor() ([]byte, []int) {
	return file_SealBattleProgressNotify_proto_rawDescGZIP(), []int{0}
}

func (x *SealBattleProgressNotify) GetSealEntityId() uint32 {
	if x != nil {
		return x.SealEntityId
	}
	return 0
}

func (x *SealBattleProgressNotify) GetMaxProgress() uint32 {
	if x != nil {
		return x.MaxProgress
	}
	return 0
}

func (x *SealBattleProgressNotify) GetSealRadius() uint32 {
	if x != nil {
		return x.SealRadius
	}
	return 0
}

func (x *SealBattleProgressNotify) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SealBattleProgressNotify) GetEndTime() uint32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_SealBattleProgressNotify_proto protoreflect.FileDescriptor

var file_SealBattleProgressNotify_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x53, 0x65, 0x61, 0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xbb, 0x01, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x6c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x65, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x6c, 0x5f, 0x72,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x61,
	0x6c, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_SealBattleProgressNotify_proto_rawDescOnce sync.Once
	file_SealBattleProgressNotify_proto_rawDescData = file_SealBattleProgressNotify_proto_rawDesc
)

func file_SealBattleProgressNotify_proto_rawDescGZIP() []byte {
	file_SealBattleProgressNotify_proto_rawDescOnce.Do(func() {
		file_SealBattleProgressNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_SealBattleProgressNotify_proto_rawDescData)
	})
	return file_SealBattleProgressNotify_proto_rawDescData
}

var file_SealBattleProgressNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SealBattleProgressNotify_proto_goTypes = []interface{}{
	(*SealBattleProgressNotify)(nil), // 0: SealBattleProgressNotify
}
var file_SealBattleProgressNotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SealBattleProgressNotify_proto_init() }
func file_SealBattleProgressNotify_proto_init() {
	if File_SealBattleProgressNotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SealBattleProgressNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SealBattleProgressNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SealBattleProgressNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SealBattleProgressNotify_proto_goTypes,
		DependencyIndexes: file_SealBattleProgressNotify_proto_depIdxs,
		MessageInfos:      file_SealBattleProgressNotify_proto_msgTypes,
	}.Build()
	File_SealBattleProgressNotify_proto = out.File
	file_SealBattleProgressNotify_proto_rawDesc = nil
	file_SealBattleProgressNotify_proto_goTypes = nil
	file_SealBattleProgressNotify_proto_depIdxs = nil
}
