// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SummerTimeDetailInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummerTimeDetailInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageMap         map[uint32]*SummerTimeStageInfo `protobuf:"bytes,3,rep,name=stage_map,json=stageMap,proto3" json:"stage_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentCloseTime uint32                          `protobuf:"varint,11,opt,name=content_close_time,json=contentCloseTime,proto3" json:"content_close_time,omitempty"`
	IsContentClosed  bool                            `protobuf:"varint,13,opt,name=is_content_closed,json=isContentClosed,proto3" json:"is_content_closed,omitempty"`
	SprintBoatInfo   *SummerTimeSprintBoatInfo       `protobuf:"bytes,4,opt,name=sprint_boat_info,json=sprintBoatInfo,proto3" json:"sprint_boat_info,omitempty"`
}

func (x *SummerTimeDetailInfo) Reset() {
	*x = SummerTimeDetailInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SummerTimeDetailInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummerTimeDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummerTimeDetailInfo) ProtoMessage() {}

func (x *SummerTimeDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_SummerTimeDetailInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummerTimeDetailInfo.ProtoReflect.Descriptor instead.
func (*SummerTimeDetailInfo) Descriptor() ([]byte, []int) {
	return file_SummerTimeDetailInfo_proto_rawDescGZIP(), []int{0}
}

func (x *SummerTimeDetailInfo) GetStageMap() map[uint32]*SummerTimeStageInfo {
	if x != nil {
		return x.StageMap
	}
	return nil
}

func (x *SummerTimeDetailInfo) GetContentCloseTime() uint32 {
	if x != nil {
		return x.ContentCloseTime
	}
	return 0
}

func (x *SummerTimeDetailInfo) GetIsContentClosed() bool {
	if x != nil {
		return x.IsContentClosed
	}
	return false
}

func (x *SummerTimeDetailInfo) GetSprintBoatInfo() *SummerTimeSprintBoatInfo {
	if x != nil {
		return x.SprintBoatInfo
	}
	return nil
}

var File_SummerTimeDetailInfo_proto protoreflect.FileDescriptor

var file_SummerTimeDetailInfo_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x53, 0x75,
	0x6d, 0x6d, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x6f,
	0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x53, 0x75,
	0x6d, 0x6d, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x02, 0x0a, 0x14, 0x53, 0x75, 0x6d, 0x6d,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x40, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4d,
	0x61, 0x70, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x43, 0x0a, 0x10,
	0x73, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x62, 0x6f, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x6f, 0x61, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0e, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x6f, 0x61, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x51, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SummerTimeDetailInfo_proto_rawDescOnce sync.Once
	file_SummerTimeDetailInfo_proto_rawDescData = file_SummerTimeDetailInfo_proto_rawDesc
)

func file_SummerTimeDetailInfo_proto_rawDescGZIP() []byte {
	file_SummerTimeDetailInfo_proto_rawDescOnce.Do(func() {
		file_SummerTimeDetailInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_SummerTimeDetailInfo_proto_rawDescData)
	})
	return file_SummerTimeDetailInfo_proto_rawDescData
}

var file_SummerTimeDetailInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SummerTimeDetailInfo_proto_goTypes = []interface{}{
	(*SummerTimeDetailInfo)(nil),     // 0: SummerTimeDetailInfo
	nil,                              // 1: SummerTimeDetailInfo.StageMapEntry
	(*SummerTimeSprintBoatInfo)(nil), // 2: SummerTimeSprintBoatInfo
	(*SummerTimeStageInfo)(nil),      // 3: SummerTimeStageInfo
}
var file_SummerTimeDetailInfo_proto_depIdxs = []int32{
	1, // 0: SummerTimeDetailInfo.stage_map:type_name -> SummerTimeDetailInfo.StageMapEntry
	2, // 1: SummerTimeDetailInfo.sprint_boat_info:type_name -> SummerTimeSprintBoatInfo
	3, // 2: SummerTimeDetailInfo.StageMapEntry.value:type_name -> SummerTimeStageInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SummerTimeDetailInfo_proto_init() }
func file_SummerTimeDetailInfo_proto_init() {
	if File_SummerTimeDetailInfo_proto != nil {
		return
	}
	file_SummerTimeSprintBoatInfo_proto_init()
	file_SummerTimeStageInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SummerTimeDetailInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummerTimeDetailInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SummerTimeDetailInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SummerTimeDetailInfo_proto_goTypes,
		DependencyIndexes: file_SummerTimeDetailInfo_proto_depIdxs,
		MessageInfos:      file_SummerTimeDetailInfo_proto_msgTypes,
	}.Build()
	File_SummerTimeDetailInfo_proto = out.File
	file_SummerTimeDetailInfo_proto_rawDesc = nil
	file_SummerTimeDetailInfo_proto_goTypes = nil
	file_SummerTimeDetailInfo_proto_depIdxs = nil
}
