// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: Unk2700_KDDPDHGPGEF_ServerRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 123
// EnetChannelId: 0
// EnetIsReliable: true
type Unk2700_KDDPDHGPGEF_ServerRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode  int32  `protobuf:"varint,6,opt,name=retcode,proto3" json:"retcode,omitempty"`
	AvatarId uint32 `protobuf:"varint,15,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	// Types that are assignable to Detail:
	//	*Unk2700_KDDPDHGPGEF_ServerRsp_SkillResponse
	//	*Unk2700_KDDPDHGPGEF_ServerRsp_ReliquaryResponse
	//	*Unk2700_KDDPDHGPGEF_ServerRsp_ElementReliquaryResponse
	Detail isUnk2700_KDDPDHGPGEF_ServerRsp_Detail `protobuf_oneof:"detail"`
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) Reset() {
	*x = Unk2700_KDDPDHGPGEF_ServerRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unk2700_KDDPDHGPGEF_ServerRsp) ProtoMessage() {}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) ProtoReflect() protoreflect.Message {
	mi := &file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unk2700_KDDPDHGPGEF_ServerRsp.ProtoReflect.Descriptor instead.
func (*Unk2700_KDDPDHGPGEF_ServerRsp) Descriptor() ([]byte, []int) {
	return file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescGZIP(), []int{0}
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) GetAvatarId() uint32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (m *Unk2700_KDDPDHGPGEF_ServerRsp) GetDetail() isUnk2700_KDDPDHGPGEF_ServerRsp_Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) GetSkillResponse() *SkillResponse {
	if x, ok := x.GetDetail().(*Unk2700_KDDPDHGPGEF_ServerRsp_SkillResponse); ok {
		return x.SkillResponse
	}
	return nil
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) GetReliquaryResponse() *ReliquaryResponse {
	if x, ok := x.GetDetail().(*Unk2700_KDDPDHGPGEF_ServerRsp_ReliquaryResponse); ok {
		return x.ReliquaryResponse
	}
	return nil
}

func (x *Unk2700_KDDPDHGPGEF_ServerRsp) GetElementReliquaryResponse() *ElementReliquaryResponse {
	if x, ok := x.GetDetail().(*Unk2700_KDDPDHGPGEF_ServerRsp_ElementReliquaryResponse); ok {
		return x.ElementReliquaryResponse
	}
	return nil
}

type isUnk2700_KDDPDHGPGEF_ServerRsp_Detail interface {
	isUnk2700_KDDPDHGPGEF_ServerRsp_Detail()
}

type Unk2700_KDDPDHGPGEF_ServerRsp_SkillResponse struct {
	SkillResponse *SkillResponse `protobuf:"bytes,1022,opt,name=skill_response,json=skillResponse,proto3,oneof"`
}

type Unk2700_KDDPDHGPGEF_ServerRsp_ReliquaryResponse struct {
	ReliquaryResponse *ReliquaryResponse `protobuf:"bytes,196,opt,name=reliquary_response,json=reliquaryResponse,proto3,oneof"`
}

type Unk2700_KDDPDHGPGEF_ServerRsp_ElementReliquaryResponse struct {
	ElementReliquaryResponse *ElementReliquaryResponse `protobuf:"bytes,167,opt,name=element_reliquary_response,json=elementReliquaryResponse,proto3,oneof"`
}

func (*Unk2700_KDDPDHGPGEF_ServerRsp_SkillResponse) isUnk2700_KDDPDHGPGEF_ServerRsp_Detail() {}

func (*Unk2700_KDDPDHGPGEF_ServerRsp_ReliquaryResponse) isUnk2700_KDDPDHGPGEF_ServerRsp_Detail() {}

func (*Unk2700_KDDPDHGPGEF_ServerRsp_ElementReliquaryResponse) isUnk2700_KDDPDHGPGEF_ServerRsp_Detail() {
}

var File_Unk2700_KDDPDHGPGEF_ServerRsp_proto protoreflect.FileDescriptor

var file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDesc = []byte{
	0x0a, 0x23, 0x55, 0x6e, 0x6b, 0x32, 0x37, 0x30, 0x30, 0x5f, 0x4b, 0x44, 0x44, 0x50, 0x44, 0x48,
	0x47, 0x50, 0x47, 0x45, 0x46, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x73, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x52, 0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x02, 0x0a, 0x1d, 0x55, 0x6e, 0x6b, 0x32, 0x37, 0x30, 0x30, 0x5f,
	0x4b, 0x44, 0x44, 0x50, 0x44, 0x48, 0x47, 0x50, 0x47, 0x45, 0x46, 0x5f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0e,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0xfe,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x12, 0x72, 0x65, 0x6c, 0x69, 0x71, 0x75,
	0x61, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0xc4, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x6c, 0x69, 0x71,
	0x75, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x1a,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72,
	0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0xa7, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x69, 0x71,
	0x75, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x18,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescOnce sync.Once
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescData = file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDesc
)

func file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescGZIP() []byte {
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescOnce.Do(func() {
		file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescData)
	})
	return file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDescData
}

var file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_goTypes = []interface{}{
	(*Unk2700_KDDPDHGPGEF_ServerRsp)(nil), // 0: Unk2700_KDDPDHGPGEF_ServerRsp
	(*SkillResponse)(nil),                 // 1: SkillResponse
	(*ReliquaryResponse)(nil),             // 2: ReliquaryResponse
	(*ElementReliquaryResponse)(nil),      // 3: ElementReliquaryResponse
}
var file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_depIdxs = []int32{
	1, // 0: Unk2700_KDDPDHGPGEF_ServerRsp.skill_response:type_name -> SkillResponse
	2, // 1: Unk2700_KDDPDHGPGEF_ServerRsp.reliquary_response:type_name -> ReliquaryResponse
	3, // 2: Unk2700_KDDPDHGPGEF_ServerRsp.element_reliquary_response:type_name -> ElementReliquaryResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_init() }
func file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_init() {
	if File_Unk2700_KDDPDHGPGEF_ServerRsp_proto != nil {
		return
	}
	file_ElementReliquaryResponse_proto_init()
	file_ReliquaryResponse_proto_init()
	file_SkillResponse_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unk2700_KDDPDHGPGEF_ServerRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Unk2700_KDDPDHGPGEF_ServerRsp_SkillResponse)(nil),
		(*Unk2700_KDDPDHGPGEF_ServerRsp_ReliquaryResponse)(nil),
		(*Unk2700_KDDPDHGPGEF_ServerRsp_ElementReliquaryResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_goTypes,
		DependencyIndexes: file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_depIdxs,
		MessageInfos:      file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_msgTypes,
	}.Build()
	File_Unk2700_KDDPDHGPGEF_ServerRsp_proto = out.File
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_rawDesc = nil
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_goTypes = nil
	file_Unk2700_KDDPDHGPGEF_ServerRsp_proto_depIdxs = nil
}
