package constant

func InitConstant() {
	InitFightPropertyConst()
	InitActionReasonConst()
	InitClimateTypeConst()
	InitElementTypeConst()
	InitEnterReasonConst()
	InitEntityIdTypeConst()
	InitEquipTypeConst()
	InitFetterStateConst()
	InitGameConstant()
	InitGrowCurveConst()
	InitItemTypeConst()
	InitLifeStateConst()
	InitMaterialTypeConst()
	InitOpenStateConst()
	InitPlayerPropertyConst()
	InitSceneTypeConst()
	InitEntityTypeConst()
	InitStaminaCostConst()
	InitWeaponTypeConst()
	InitGCGTokenConst()
	InitItemConstantConst()
}
