package constant

const (
	GADGET_STATE_DEFAULT           = 0
	GADGET_STATE_GATHER_DROP       = 1
	GADGET_STATE_CHEST_LOCKED      = 101
	GADGET_STATE_CHEST_OPENED      = 102
	GADGET_STATE_CHEST_TRAP        = 103
	GADGET_STATE_CHEST_BRAMBLE     = 104
	GADGET_STATE_CHEST_FROZEN      = 105
	GADGET_STATE_CHEST_ROCK        = 106
	GADGET_STATE_GEAR_START        = 201
	GADGET_STATE_GEAR_STOP         = 202
	GADGET_STATE_GEAR_ACTION1      = 203
	GADGET_STATE_GEAR_ACTION2      = 204
	GADGET_STATE_CRYSTAL_RESONATE1 = 301
	GADGET_STATE_CRYSTAL_RESONATE2 = 302
	GADGET_STATE_CRYSTAL_EXPLODE   = 303
	GADGET_STATE_CRYSTAL_DRAIN     = 304
	GADGET_STATE_STATUE_ACTIVE     = 401
	GADGET_STATE_ACTION01          = 901
	GADGET_STATE_ACTION02          = 902
	GADGET_STATE_ACTION03          = 903
)
