package constant

const (
	ITEM_TYPE_NONE      uint16 = 0
	ITEM_TYPE_VIRTUAL   uint16 = 1
	ITEM_TYPE_MATERIAL  uint16 = 2
	ITEM_TYPE_RELIQUARY uint16 = 3
	ITEM_TYPE_WEAPON    uint16 = 4
	ITEM_TYPE_DISPLAY   uint16 = 5
	ITEM_TYPE_FURNITURE uint16 = 6
)
