package constant

const (
	// 虚拟物品
	ITEM_ID_HCOIN         uint32 = 201 // 原石
	ITEM_ID_SCOIN         uint32 = 202 // 摩拉
	ITEM_ID_MCOIN         uint32 = 203 // 创世结晶
	ITEM_ID_RESIN         uint32 = 106 // 树脂
	ITEM_ID_LEGENDARY_KEY uint32 = 207 // 传说任务钥匙
	ITEM_ID_HOME_COIN     uint32 = 204 // 洞天宝钱
	ITEM_ID_PLAYER_EXP    uint32 = 102 // 冒险阅历
	// 武器强化物品
	ITEM_ID_WEAPON_UPGRADE_MAGIC  uint32 = 104013 // 精锻用魔矿
	ITEM_ID_WEAPON_UPGRADE_GOOD   uint32 = 104012 // 精锻用良矿
	ITEM_ID_WEAPON_UPGRADE_MOTLEY uint32 = 104011 // 精锻用杂矿
)

// 虚拟物品对应玩家的属性
var VIRTUAL_ITEM_PROP map[uint32]uint16

// 武器强化返还材料列表
var WEAPON_UPGRADE_MATERIAL []uint32

func init() {
	VIRTUAL_ITEM_PROP = map[uint32]uint16{
		ITEM_ID_HCOIN:         PLAYER_PROP_PLAYER_HCOIN,
		ITEM_ID_SCOIN:         PLAYER_PROP_PLAYER_SCOIN,
		ITEM_ID_MCOIN:         PLAYER_PROP_PLAYER_MCOIN,
		ITEM_ID_RESIN:         PLAYER_PROP_PLAYER_RESIN,
		ITEM_ID_LEGENDARY_KEY: PLAYER_PROP_PLAYER_LEGENDARY_KEY,
		ITEM_ID_HOME_COIN:     PLAYER_PROP_PLAYER_HOME_COIN,
		ITEM_ID_PLAYER_EXP:    PLAYER_PROP_PLAYER_EXP,
	}
	WEAPON_UPGRADE_MATERIAL = []uint32{
		ITEM_ID_WEAPON_UPGRADE_MAGIC,
		ITEM_ID_WEAPON_UPGRADE_GOOD,
		ITEM_ID_WEAPON_UPGRADE_MOTLEY,
	}
}
