package constant

const (
	ITEM_TYPE_NONE      = 0
	ITEM_TYPE_VIRTUAL   = 1
	ITEM_TYPE_MATERIAL  = 2
	ITEM_TYPE_RELIQUARY = 3
	ITEM_TYPE_WEAPON    = 4
	ITEM_TYPE_DISPLAY   = 5
	ITEM_TYPE_FURNITURE = 6
)
