package constant

const (
	MATERIAL_TYPE_NONE                    = 0
	MATERIAL_TYPE_FOOD                    = 1
	MATERIAL_TYPE_QUEST                   = 2
	MATERIAL_TYPE_EXCHANGE                = 4
	MATERIAL_TYPE_CONSUME                 = 5
	MATERIAL_TYPE_EXP_FRUIT               = 6
	MATERIAL_TYPE_AVATAR                  = 7
	MATERIAL_TYPE_ADSORBATE               = 8
	MATERIAL_TYPE_CRICKET                 = 9
	MATERIAL_TYPE_ELEM_CRYSTAL            = 10
	MATERIAL_TYPE_WEAPON_EXP_STONE        = 11
	MATERIAL_TYPE_CHEST                   = 12
	MATERIAL_TYPE_RELIQUARY_MATERIAL      = 13
	MATERIAL_TYPE_AVATAR_MATERIAL         = 14
	MATERIAL_TYPE_NOTICE_ADD_HP           = 15
	MATERIAL_TYPE_SEA_LAMP                = 16
	MATERIAL_TYPE_SELECTABLE_CHEST        = 17
	MATERIAL_TYPE_FLYCLOAK                = 18
	MATERIAL_TYPE_NAMECARD                = 19
	MATERIAL_TYPE_TALENT                  = 20
	MATERIAL_TYPE_WIDGET                  = 21
	MATERIAL_TYPE_CHEST_BATCH_USE         = 22
	MATERIAL_TYPE_FAKE_ABSORBATE          = 23
	MATERIAL_TYPE_CONSUME_BATCH_USE       = 24
	MATERIAL_TYPE_WOOD                    = 25
	MATERIAL_TYPE_FURNITURE_FORMULA       = 27
	MATERIAL_TYPE_CHANNELLER_SLAB_BUFF    = 28
	MATERIAL_TYPE_FURNITURE_SUITE_FORMULA = 29
	MATERIAL_TYPE_COSTUME                 = 30
)
