// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: CheckUgcUpdateRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 6345
// EnetChannelId: 0
// EnetIsReliable: true
type CheckUgcUpdateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateUgcGuidList []uint64 `protobuf:"varint,15,rep,packed,name=update_ugc_guid_list,json=updateUgcGuidList,proto3" json:"update_ugc_guid_list,omitempty"`
	Retcode           int32    `protobuf:"varint,10,opt,name=retcode,proto3" json:"retcode,omitempty"`
	UgcType           UgcType  `protobuf:"varint,12,opt,name=ugc_type,json=ugcType,proto3,enum=proto.UgcType" json:"ugc_type,omitempty"`
}

func (x *CheckUgcUpdateRsp) Reset() {
	*x = CheckUgcUpdateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CheckUgcUpdateRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUgcUpdateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUgcUpdateRsp) ProtoMessage() {}

func (x *CheckUgcUpdateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_CheckUgcUpdateRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUgcUpdateRsp.ProtoReflect.Descriptor instead.
func (*CheckUgcUpdateRsp) Descriptor() ([]byte, []int) {
	return file_CheckUgcUpdateRsp_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUgcUpdateRsp) GetUpdateUgcGuidList() []uint64 {
	if x != nil {
		return x.UpdateUgcGuidList
	}
	return nil
}

func (x *CheckUgcUpdateRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *CheckUgcUpdateRsp) GetUgcType() UgcType {
	if x != nil {
		return x.UgcType
	}
	return UgcType_UGC_TYPE_NONE
}

var File_CheckUgcUpdateRsp_proto protoreflect.FileDescriptor

var file_CheckUgcUpdateRsp_proto_rawDesc = []byte{
	0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x67, 0x63, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0d, 0x55, 0x67, 0x63, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x89, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x67, 0x63, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x14, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x75, 0x67, 0x63, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0f, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x67, 0x63, 0x47, 0x75,
	0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x29, 0x0a, 0x08, 0x75, 0x67, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x67, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x75, 0x67, 0x63, 0x54, 0x79, 0x70, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CheckUgcUpdateRsp_proto_rawDescOnce sync.Once
	file_CheckUgcUpdateRsp_proto_rawDescData = file_CheckUgcUpdateRsp_proto_rawDesc
)

func file_CheckUgcUpdateRsp_proto_rawDescGZIP() []byte {
	file_CheckUgcUpdateRsp_proto_rawDescOnce.Do(func() {
		file_CheckUgcUpdateRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_CheckUgcUpdateRsp_proto_rawDescData)
	})
	return file_CheckUgcUpdateRsp_proto_rawDescData
}

var file_CheckUgcUpdateRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CheckUgcUpdateRsp_proto_goTypes = []interface{}{
	(*CheckUgcUpdateRsp)(nil), // 0: proto.CheckUgcUpdateRsp
	(UgcType)(0),              // 1: proto.UgcType
}
var file_CheckUgcUpdateRsp_proto_depIdxs = []int32{
	1, // 0: proto.CheckUgcUpdateRsp.ugc_type:type_name -> proto.UgcType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_CheckUgcUpdateRsp_proto_init() }
func file_CheckUgcUpdateRsp_proto_init() {
	if File_CheckUgcUpdateRsp_proto != nil {
		return
	}
	file_UgcType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CheckUgcUpdateRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUgcUpdateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CheckUgcUpdateRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CheckUgcUpdateRsp_proto_goTypes,
		DependencyIndexes: file_CheckUgcUpdateRsp_proto_depIdxs,
		MessageInfos:      file_CheckUgcUpdateRsp_proto_msgTypes,
	}.Build()
	File_CheckUgcUpdateRsp_proto = out.File
	file_CheckUgcUpdateRsp_proto_rawDesc = nil
	file_CheckUgcUpdateRsp_proto_goTypes = nil
	file_CheckUgcUpdateRsp_proto_depIdxs = nil
}
