// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: CityReputationQuestInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityReputationQuestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOpen                     bool     `protobuf:"varint,2,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	TakenParentQuestRewardList []uint32 `protobuf:"varint,12,rep,packed,name=taken_parent_quest_reward_list,json=takenParentQuestRewardList,proto3" json:"taken_parent_quest_reward_list,omitempty"`
	FinishedParentQuestList    []uint32 `protobuf:"varint,7,rep,packed,name=finished_parent_quest_list,json=finishedParentQuestList,proto3" json:"finished_parent_quest_list,omitempty"`
}

func (x *CityReputationQuestInfo) Reset() {
	*x = CityReputationQuestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CityReputationQuestInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityReputationQuestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityReputationQuestInfo) ProtoMessage() {}

func (x *CityReputationQuestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_CityReputationQuestInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityReputationQuestInfo.ProtoReflect.Descriptor instead.
func (*CityReputationQuestInfo) Descriptor() ([]byte, []int) {
	return file_CityReputationQuestInfo_proto_rawDescGZIP(), []int{0}
}

func (x *CityReputationQuestInfo) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *CityReputationQuestInfo) GetTakenParentQuestRewardList() []uint32 {
	if x != nil {
		return x.TakenParentQuestRewardList
	}
	return nil
}

func (x *CityReputationQuestInfo) GetFinishedParentQuestList() []uint32 {
	if x != nil {
		return x.FinishedParentQuestList
	}
	return nil
}

var File_CityReputationQuestInfo_proto protoreflect.FileDescriptor

var file_CityReputationQuestInfo_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x17, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x42, 0x0a, 0x1e, 0x74,
	0x61, 0x6b, 0x65, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x1a, 0x74, 0x61, 0x6b, 0x65, 0x6e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x1a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x17, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CityReputationQuestInfo_proto_rawDescOnce sync.Once
	file_CityReputationQuestInfo_proto_rawDescData = file_CityReputationQuestInfo_proto_rawDesc
)

func file_CityReputationQuestInfo_proto_rawDescGZIP() []byte {
	file_CityReputationQuestInfo_proto_rawDescOnce.Do(func() {
		file_CityReputationQuestInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_CityReputationQuestInfo_proto_rawDescData)
	})
	return file_CityReputationQuestInfo_proto_rawDescData
}

var file_CityReputationQuestInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CityReputationQuestInfo_proto_goTypes = []interface{}{
	(*CityReputationQuestInfo)(nil), // 0: proto.CityReputationQuestInfo
}
var file_CityReputationQuestInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CityReputationQuestInfo_proto_init() }
func file_CityReputationQuestInfo_proto_init() {
	if File_CityReputationQuestInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CityReputationQuestInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityReputationQuestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CityReputationQuestInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CityReputationQuestInfo_proto_goTypes,
		DependencyIndexes: file_CityReputationQuestInfo_proto_depIdxs,
		MessageInfos:      file_CityReputationQuestInfo_proto_msgTypes,
	}.Build()
	File_CityReputationQuestInfo_proto = out.File
	file_CityReputationQuestInfo_proto_rawDesc = nil
	file_CityReputationQuestInfo_proto_goTypes = nil
	file_CityReputationQuestInfo_proto_depIdxs = nil
}
