// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: CrystalLinkDungeonInfoNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 8858
// EnetChannelId: 0
// EnetIsReliable: true
type CrystalLinkDungeonInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuffInfoList          []*CrystalLinkBuffInfo          `protobuf:"bytes,8,rep,name=buff_info_list,json=buffInfoList,proto3" json:"buff_info_list,omitempty"`
	LevelId               uint32                          `protobuf:"varint,1,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	IsUpperPart           bool                            `protobuf:"varint,15,opt,name=is_upper_part,json=isUpperPart,proto3" json:"is_upper_part,omitempty"`
	DifficultyId          uint32                          `protobuf:"varint,11,opt,name=difficulty_id,json=difficultyId,proto3" json:"difficulty_id,omitempty"`
	DungeonAvatarInfoList []*CrystalLinkDungeonAvatarInfo `protobuf:"bytes,3,rep,name=dungeon_avatar_info_list,json=dungeonAvatarInfoList,proto3" json:"dungeon_avatar_info_list,omitempty"`
	InitGalleryProgress   uint32                          `protobuf:"varint,7,opt,name=init_gallery_progress,json=initGalleryProgress,proto3" json:"init_gallery_progress,omitempty"`
}

func (x *CrystalLinkDungeonInfoNotify) Reset() {
	*x = CrystalLinkDungeonInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CrystalLinkDungeonInfoNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrystalLinkDungeonInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrystalLinkDungeonInfoNotify) ProtoMessage() {}

func (x *CrystalLinkDungeonInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_CrystalLinkDungeonInfoNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrystalLinkDungeonInfoNotify.ProtoReflect.Descriptor instead.
func (*CrystalLinkDungeonInfoNotify) Descriptor() ([]byte, []int) {
	return file_CrystalLinkDungeonInfoNotify_proto_rawDescGZIP(), []int{0}
}

func (x *CrystalLinkDungeonInfoNotify) GetBuffInfoList() []*CrystalLinkBuffInfo {
	if x != nil {
		return x.BuffInfoList
	}
	return nil
}

func (x *CrystalLinkDungeonInfoNotify) GetLevelId() uint32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *CrystalLinkDungeonInfoNotify) GetIsUpperPart() bool {
	if x != nil {
		return x.IsUpperPart
	}
	return false
}

func (x *CrystalLinkDungeonInfoNotify) GetDifficultyId() uint32 {
	if x != nil {
		return x.DifficultyId
	}
	return 0
}

func (x *CrystalLinkDungeonInfoNotify) GetDungeonAvatarInfoList() []*CrystalLinkDungeonAvatarInfo {
	if x != nil {
		return x.DungeonAvatarInfoList
	}
	return nil
}

func (x *CrystalLinkDungeonInfoNotify) GetInitGalleryProgress() uint32 {
	if x != nil {
		return x.InitGalleryProgress
	}
	return 0
}

var File_CrystalLinkDungeonInfoNotify_proto protoreflect.FileDescriptor

var file_CrystalLinkDungeonInfoNotify_proto_rawDesc = []byte{
	0x0a, 0x22, 0x43, 0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x75, 0x6e,
	0x67, 0x65, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x43, 0x72, 0x79,
	0x73, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x43, 0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x4c,
	0x69, 0x6e, 0x6b, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x02, 0x0a, 0x1c, 0x43,
	0x72, 0x79, 0x73, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x40, 0x0a, 0x0e, 0x62,
	0x75, 0x66, 0x66, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x79, 0x73,
	0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x62, 0x75, 0x66, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x75,
	0x70, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x69, 0x73, 0x55, 0x70, 0x70, 0x65, 0x72, 0x50, 0x61, 0x72, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x5c, 0x0a, 0x18, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x79, 0x73,
	0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x15, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f,
	0x6e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x32, 0x0a, 0x15, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x5f,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13,
	0x69, 0x6e, 0x69, 0x74, 0x47, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CrystalLinkDungeonInfoNotify_proto_rawDescOnce sync.Once
	file_CrystalLinkDungeonInfoNotify_proto_rawDescData = file_CrystalLinkDungeonInfoNotify_proto_rawDesc
)

func file_CrystalLinkDungeonInfoNotify_proto_rawDescGZIP() []byte {
	file_CrystalLinkDungeonInfoNotify_proto_rawDescOnce.Do(func() {
		file_CrystalLinkDungeonInfoNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_CrystalLinkDungeonInfoNotify_proto_rawDescData)
	})
	return file_CrystalLinkDungeonInfoNotify_proto_rawDescData
}

var file_CrystalLinkDungeonInfoNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CrystalLinkDungeonInfoNotify_proto_goTypes = []interface{}{
	(*CrystalLinkDungeonInfoNotify)(nil), // 0: proto.CrystalLinkDungeonInfoNotify
	(*CrystalLinkBuffInfo)(nil),          // 1: proto.CrystalLinkBuffInfo
	(*CrystalLinkDungeonAvatarInfo)(nil), // 2: proto.CrystalLinkDungeonAvatarInfo
}
var file_CrystalLinkDungeonInfoNotify_proto_depIdxs = []int32{
	1, // 0: proto.CrystalLinkDungeonInfoNotify.buff_info_list:type_name -> proto.CrystalLinkBuffInfo
	2, // 1: proto.CrystalLinkDungeonInfoNotify.dungeon_avatar_info_list:type_name -> proto.CrystalLinkDungeonAvatarInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CrystalLinkDungeonInfoNotify_proto_init() }
func file_CrystalLinkDungeonInfoNotify_proto_init() {
	if File_CrystalLinkDungeonInfoNotify_proto != nil {
		return
	}
	file_CrystalLinkBuffInfo_proto_init()
	file_CrystalLinkDungeonAvatarInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CrystalLinkDungeonInfoNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrystalLinkDungeonInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CrystalLinkDungeonInfoNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CrystalLinkDungeonInfoNotify_proto_goTypes,
		DependencyIndexes: file_CrystalLinkDungeonInfoNotify_proto_depIdxs,
		MessageInfos:      file_CrystalLinkDungeonInfoNotify_proto_msgTypes,
	}.Build()
	File_CrystalLinkDungeonInfoNotify_proto = out.File
	file_CrystalLinkDungeonInfoNotify_proto_rawDesc = nil
	file_CrystalLinkDungeonInfoNotify_proto_goTypes = nil
	file_CrystalLinkDungeonInfoNotify_proto_depIdxs = nil
}
