// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: CustomDungeonResultInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomDungeonResultInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLiked            bool                    `protobuf:"varint,12,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	GotCoinNum         uint32                  `protobuf:"varint,9,opt,name=got_coin_num,json=gotCoinNum,proto3" json:"got_coin_num,omitempty"`
	ChildChallengeList []*ChallengeBrief       `protobuf:"bytes,6,rep,name=child_challenge_list,json=childChallengeList,proto3" json:"child_challenge_list,omitempty"`
	DungeonGuid        uint64                  `protobuf:"varint,3,opt,name=dungeon_guid,json=dungeonGuid,proto3" json:"dungeon_guid,omitempty"`
	FinishType         CustomDungeonFinishType `protobuf:"varint,7,opt,name=finish_type,json=finishType,proto3,enum=proto.CustomDungeonFinishType" json:"finish_type,omitempty"`
	TimeCost           uint32                  `protobuf:"varint,11,opt,name=time_cost,json=timeCost,proto3" json:"time_cost,omitempty"`
	IsArriveFinish     bool                    `protobuf:"varint,2,opt,name=is_arrive_finish,json=isArriveFinish,proto3" json:"is_arrive_finish,omitempty"`
	IsStored           bool                    `protobuf:"varint,14,opt,name=is_stored,json=isStored,proto3" json:"is_stored,omitempty"`
}

func (x *CustomDungeonResultInfo) Reset() {
	*x = CustomDungeonResultInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CustomDungeonResultInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomDungeonResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomDungeonResultInfo) ProtoMessage() {}

func (x *CustomDungeonResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_CustomDungeonResultInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomDungeonResultInfo.ProtoReflect.Descriptor instead.
func (*CustomDungeonResultInfo) Descriptor() ([]byte, []int) {
	return file_CustomDungeonResultInfo_proto_rawDescGZIP(), []int{0}
}

func (x *CustomDungeonResultInfo) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *CustomDungeonResultInfo) GetGotCoinNum() uint32 {
	if x != nil {
		return x.GotCoinNum
	}
	return 0
}

func (x *CustomDungeonResultInfo) GetChildChallengeList() []*ChallengeBrief {
	if x != nil {
		return x.ChildChallengeList
	}
	return nil
}

func (x *CustomDungeonResultInfo) GetDungeonGuid() uint64 {
	if x != nil {
		return x.DungeonGuid
	}
	return 0
}

func (x *CustomDungeonResultInfo) GetFinishType() CustomDungeonFinishType {
	if x != nil {
		return x.FinishType
	}
	return CustomDungeonFinishType_CUSTOM_DUNGEON_FINISH_TYPE_PLAY_NORMAL
}

func (x *CustomDungeonResultInfo) GetTimeCost() uint32 {
	if x != nil {
		return x.TimeCost
	}
	return 0
}

func (x *CustomDungeonResultInfo) GetIsArriveFinish() bool {
	if x != nil {
		return x.IsArriveFinish
	}
	return false
}

func (x *CustomDungeonResultInfo) GetIsStored() bool {
	if x != nil {
		return x.IsStored
	}
	return false
}

var File_CustomDungeonResultInfo_proto protoreflect.FileDescriptor

var file_CustomDungeonResultInfo_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x02, 0x0a, 0x17,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x6c, 0x69,
	0x6b, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x69, 0x6b,
	0x65, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x6f, 0x74, 0x43, 0x6f, 0x69,
	0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x47, 0x0a, 0x14, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x12, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x47, 0x75, 0x69, 0x64,
	0x12, 0x3f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x10, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x41, 0x72, 0x72, 0x69,
	0x76, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CustomDungeonResultInfo_proto_rawDescOnce sync.Once
	file_CustomDungeonResultInfo_proto_rawDescData = file_CustomDungeonResultInfo_proto_rawDesc
)

func file_CustomDungeonResultInfo_proto_rawDescGZIP() []byte {
	file_CustomDungeonResultInfo_proto_rawDescOnce.Do(func() {
		file_CustomDungeonResultInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_CustomDungeonResultInfo_proto_rawDescData)
	})
	return file_CustomDungeonResultInfo_proto_rawDescData
}

var file_CustomDungeonResultInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CustomDungeonResultInfo_proto_goTypes = []interface{}{
	(*CustomDungeonResultInfo)(nil), // 0: proto.CustomDungeonResultInfo
	(*ChallengeBrief)(nil),          // 1: proto.ChallengeBrief
	(CustomDungeonFinishType)(0),    // 2: proto.CustomDungeonFinishType
}
var file_CustomDungeonResultInfo_proto_depIdxs = []int32{
	1, // 0: proto.CustomDungeonResultInfo.child_challenge_list:type_name -> proto.ChallengeBrief
	2, // 1: proto.CustomDungeonResultInfo.finish_type:type_name -> proto.CustomDungeonFinishType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CustomDungeonResultInfo_proto_init() }
func file_CustomDungeonResultInfo_proto_init() {
	if File_CustomDungeonResultInfo_proto != nil {
		return
	}
	file_ChallengeBrief_proto_init()
	file_CustomDungeonFinishType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_CustomDungeonResultInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomDungeonResultInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CustomDungeonResultInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CustomDungeonResultInfo_proto_goTypes,
		DependencyIndexes: file_CustomDungeonResultInfo_proto_depIdxs,
		MessageInfos:      file_CustomDungeonResultInfo_proto_msgTypes,
	}.Build()
	File_CustomDungeonResultInfo_proto = out.File
	file_CustomDungeonResultInfo_proto_rawDesc = nil
	file_CustomDungeonResultInfo_proto_goTypes = nil
	file_CustomDungeonResultInfo_proto_depIdxs = nil
}
