// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: EvtBeingHitInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvtBeingHitInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId       uint32        `protobuf:"varint,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	AttackResult *AttackResult `protobuf:"bytes,7,opt,name=attack_result,json=attackResult,proto3" json:"attack_result,omitempty"`
	FrameNum     uint32        `protobuf:"varint,4,opt,name=frame_num,json=frameNum,proto3" json:"frame_num,omitempty"`
}

func (x *EvtBeingHitInfo) Reset() {
	*x = EvtBeingHitInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EvtBeingHitInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvtBeingHitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvtBeingHitInfo) ProtoMessage() {}

func (x *EvtBeingHitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_EvtBeingHitInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvtBeingHitInfo.ProtoReflect.Descriptor instead.
func (*EvtBeingHitInfo) Descriptor() ([]byte, []int) {
	return file_EvtBeingHitInfo_proto_rawDescGZIP(), []int{0}
}

func (x *EvtBeingHitInfo) GetPeerId() uint32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *EvtBeingHitInfo) GetAttackResult() *AttackResult {
	if x != nil {
		return x.AttackResult
	}
	return nil
}

func (x *EvtBeingHitInfo) GetFrameNum() uint32 {
	if x != nil {
		return x.FrameNum
	}
	return 0
}

var File_EvtBeingHitInfo_proto protoreflect.FileDescriptor

var file_EvtBeingHitInfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x45, 0x76, 0x74, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x45, 0x76, 0x74, 0x42, 0x65, 0x69, 0x6e, 0x67, 0x48,
	0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x38, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_EvtBeingHitInfo_proto_rawDescOnce sync.Once
	file_EvtBeingHitInfo_proto_rawDescData = file_EvtBeingHitInfo_proto_rawDesc
)

func file_EvtBeingHitInfo_proto_rawDescGZIP() []byte {
	file_EvtBeingHitInfo_proto_rawDescOnce.Do(func() {
		file_EvtBeingHitInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_EvtBeingHitInfo_proto_rawDescData)
	})
	return file_EvtBeingHitInfo_proto_rawDescData
}

var file_EvtBeingHitInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EvtBeingHitInfo_proto_goTypes = []interface{}{
	(*EvtBeingHitInfo)(nil), // 0: proto.EvtBeingHitInfo
	(*AttackResult)(nil),    // 1: proto.AttackResult
}
var file_EvtBeingHitInfo_proto_depIdxs = []int32{
	1, // 0: proto.EvtBeingHitInfo.attack_result:type_name -> proto.AttackResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_EvtBeingHitInfo_proto_init() }
func file_EvtBeingHitInfo_proto_init() {
	if File_EvtBeingHitInfo_proto != nil {
		return
	}
	file_AttackResult_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_EvtBeingHitInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvtBeingHitInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EvtBeingHitInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EvtBeingHitInfo_proto_goTypes,
		DependencyIndexes: file_EvtBeingHitInfo_proto_depIdxs,
		MessageInfos:      file_EvtBeingHitInfo_proto_msgTypes,
	}.Build()
	File_EvtBeingHitInfo_proto = out.File
	file_EvtBeingHitInfo_proto_rawDesc = nil
	file_EvtBeingHitInfo_proto_goTypes = nil
	file_EvtBeingHitInfo_proto_depIdxs = nil
}
