// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: FungusTrainingProgressDetail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FungusTrainingProgressDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurRound               uint32                             `protobuf:"varint,9,opt,name=cur_round,json=curRound,proto3" json:"cur_round,omitempty"`
	DungeonId              uint32                             `protobuf:"varint,10,opt,name=dungeon_id,json=dungeonId,proto3" json:"dungeon_id,omitempty"`
	MonsterPoolPreviewList []*FungusTrainingPoolPreviewDetail `protobuf:"bytes,5,rep,name=monster_pool_preview_list,json=monsterPoolPreviewList,proto3" json:"monster_pool_preview_list,omitempty"`
	MonsterDetailList      []*FungusFighterMonsterDetail      `protobuf:"bytes,6,rep,name=monster_detail_list,json=monsterDetailList,proto3" json:"monster_detail_list,omitempty"`
	TotalUsedTime          uint32                             `protobuf:"varint,7,opt,name=total_used_time,json=totalUsedTime,proto3" json:"total_used_time,omitempty"`
	BackupMonsterList      []uint32                           `protobuf:"varint,4,rep,packed,name=backup_monster_list,json=backupMonsterList,proto3" json:"backup_monster_list,omitempty"`
	ChoosenMonsterList     []uint32                           `protobuf:"varint,8,rep,packed,name=choosen_monster_list,json=choosenMonsterList,proto3" json:"choosen_monster_list,omitempty"`
}

func (x *FungusTrainingProgressDetail) Reset() {
	*x = FungusTrainingProgressDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FungusTrainingProgressDetail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FungusTrainingProgressDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FungusTrainingProgressDetail) ProtoMessage() {}

func (x *FungusTrainingProgressDetail) ProtoReflect() protoreflect.Message {
	mi := &file_FungusTrainingProgressDetail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FungusTrainingProgressDetail.ProtoReflect.Descriptor instead.
func (*FungusTrainingProgressDetail) Descriptor() ([]byte, []int) {
	return file_FungusTrainingProgressDetail_proto_rawDescGZIP(), []int{0}
}

func (x *FungusTrainingProgressDetail) GetCurRound() uint32 {
	if x != nil {
		return x.CurRound
	}
	return 0
}

func (x *FungusTrainingProgressDetail) GetDungeonId() uint32 {
	if x != nil {
		return x.DungeonId
	}
	return 0
}

func (x *FungusTrainingProgressDetail) GetMonsterPoolPreviewList() []*FungusTrainingPoolPreviewDetail {
	if x != nil {
		return x.MonsterPoolPreviewList
	}
	return nil
}

func (x *FungusTrainingProgressDetail) GetMonsterDetailList() []*FungusFighterMonsterDetail {
	if x != nil {
		return x.MonsterDetailList
	}
	return nil
}

func (x *FungusTrainingProgressDetail) GetTotalUsedTime() uint32 {
	if x != nil {
		return x.TotalUsedTime
	}
	return 0
}

func (x *FungusTrainingProgressDetail) GetBackupMonsterList() []uint32 {
	if x != nil {
		return x.BackupMonsterList
	}
	return nil
}

func (x *FungusTrainingProgressDetail) GetChoosenMonsterList() []uint32 {
	if x != nil {
		return x.ChoosenMonsterList
	}
	return nil
}

var File_FungusTrainingProgressDetail_proto protoreflect.FileDescriptor

var file_FungusTrainingProgressDetail_proto_rawDesc = []byte{
	0x0a, 0x22, 0x46, 0x75, 0x6e, 0x67, 0x75, 0x73, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x46, 0x75, 0x6e,
	0x67, 0x75, 0x73, 0x46, 0x69, 0x67, 0x68, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x46,
	0x75, 0x6e, 0x67, 0x75, 0x73, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f,
	0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x03, 0x0a, 0x1c, 0x46, 0x75, 0x6e, 0x67, 0x75, 0x73, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x61, 0x0a, 0x19, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x6f,
	0x6c, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x75, 0x6e,
	0x67, 0x75, 0x73, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6f, 0x6c, 0x50,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x16, 0x6d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x13, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x75, 0x6e, 0x67, 0x75, 0x73,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x11, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x13, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x11, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x14, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x6e, 0x5f, 0x6d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x12, 0x63,
	0x68, 0x6f, 0x6f, 0x73, 0x65, 0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FungusTrainingProgressDetail_proto_rawDescOnce sync.Once
	file_FungusTrainingProgressDetail_proto_rawDescData = file_FungusTrainingProgressDetail_proto_rawDesc
)

func file_FungusTrainingProgressDetail_proto_rawDescGZIP() []byte {
	file_FungusTrainingProgressDetail_proto_rawDescOnce.Do(func() {
		file_FungusTrainingProgressDetail_proto_rawDescData = protoimpl.X.CompressGZIP(file_FungusTrainingProgressDetail_proto_rawDescData)
	})
	return file_FungusTrainingProgressDetail_proto_rawDescData
}

var file_FungusTrainingProgressDetail_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_FungusTrainingProgressDetail_proto_goTypes = []interface{}{
	(*FungusTrainingProgressDetail)(nil),    // 0: proto.FungusTrainingProgressDetail
	(*FungusTrainingPoolPreviewDetail)(nil), // 1: proto.FungusTrainingPoolPreviewDetail
	(*FungusFighterMonsterDetail)(nil),      // 2: proto.FungusFighterMonsterDetail
}
var file_FungusTrainingProgressDetail_proto_depIdxs = []int32{
	1, // 0: proto.FungusTrainingProgressDetail.monster_pool_preview_list:type_name -> proto.FungusTrainingPoolPreviewDetail
	2, // 1: proto.FungusTrainingProgressDetail.monster_detail_list:type_name -> proto.FungusFighterMonsterDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_FungusTrainingProgressDetail_proto_init() }
func file_FungusTrainingProgressDetail_proto_init() {
	if File_FungusTrainingProgressDetail_proto != nil {
		return
	}
	file_FungusFighterMonsterDetail_proto_init()
	file_FungusTrainingPoolPreviewDetail_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_FungusTrainingProgressDetail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FungusTrainingProgressDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FungusTrainingProgressDetail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FungusTrainingProgressDetail_proto_goTypes,
		DependencyIndexes: file_FungusTrainingProgressDetail_proto_depIdxs,
		MessageInfos:      file_FungusTrainingProgressDetail_proto_msgTypes,
	}.Build()
	File_FungusTrainingProgressDetail_proto = out.File
	file_FungusTrainingProgressDetail_proto_rawDesc = nil
	file_FungusTrainingProgressDetail_proto_goTypes = nil
	file_FungusTrainingProgressDetail_proto_depIdxs = nil
}
