// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: GCGSkillPreviewElementReactionInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GCGSkillPreviewElementReactionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FreshList    []uint32                       `protobuf:"varint,8,rep,packed,name=fresh_list,json=freshList,proto3" json:"fresh_list,omitempty"`
	SourceList   []uint32                       `protobuf:"varint,2,rep,packed,name=source_list,json=sourceList,proto3" json:"source_list,omitempty"`
	ReactionList []*GCGSkillPreviewReactionInfo `protobuf:"bytes,14,rep,name=reaction_list,json=reactionList,proto3" json:"reaction_list,omitempty"`
}

func (x *GCGSkillPreviewElementReactionInfo) Reset() {
	*x = GCGSkillPreviewElementReactionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GCGSkillPreviewElementReactionInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GCGSkillPreviewElementReactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCGSkillPreviewElementReactionInfo) ProtoMessage() {}

func (x *GCGSkillPreviewElementReactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GCGSkillPreviewElementReactionInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCGSkillPreviewElementReactionInfo.ProtoReflect.Descriptor instead.
func (*GCGSkillPreviewElementReactionInfo) Descriptor() ([]byte, []int) {
	return file_GCGSkillPreviewElementReactionInfo_proto_rawDescGZIP(), []int{0}
}

func (x *GCGSkillPreviewElementReactionInfo) GetFreshList() []uint32 {
	if x != nil {
		return x.FreshList
	}
	return nil
}

func (x *GCGSkillPreviewElementReactionInfo) GetSourceList() []uint32 {
	if x != nil {
		return x.SourceList
	}
	return nil
}

func (x *GCGSkillPreviewElementReactionInfo) GetReactionList() []*GCGSkillPreviewReactionInfo {
	if x != nil {
		return x.ReactionList
	}
	return nil
}

var File_GCGSkillPreviewElementReactionInfo_proto protoreflect.FileDescriptor

var file_GCGSkillPreviewElementReactionInfo_proto_rawDesc = []byte{
	0x0a, 0x28, 0x47, 0x43, 0x47, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x21, 0x47, 0x43, 0x47, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x01, 0x0a, 0x22, 0x47, 0x43, 0x47, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x09, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0d, 0x72,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x43, 0x47, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GCGSkillPreviewElementReactionInfo_proto_rawDescOnce sync.Once
	file_GCGSkillPreviewElementReactionInfo_proto_rawDescData = file_GCGSkillPreviewElementReactionInfo_proto_rawDesc
)

func file_GCGSkillPreviewElementReactionInfo_proto_rawDescGZIP() []byte {
	file_GCGSkillPreviewElementReactionInfo_proto_rawDescOnce.Do(func() {
		file_GCGSkillPreviewElementReactionInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_GCGSkillPreviewElementReactionInfo_proto_rawDescData)
	})
	return file_GCGSkillPreviewElementReactionInfo_proto_rawDescData
}

var file_GCGSkillPreviewElementReactionInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GCGSkillPreviewElementReactionInfo_proto_goTypes = []interface{}{
	(*GCGSkillPreviewElementReactionInfo)(nil), // 0: proto.GCGSkillPreviewElementReactionInfo
	(*GCGSkillPreviewReactionInfo)(nil),        // 1: proto.GCGSkillPreviewReactionInfo
}
var file_GCGSkillPreviewElementReactionInfo_proto_depIdxs = []int32{
	1, // 0: proto.GCGSkillPreviewElementReactionInfo.reaction_list:type_name -> proto.GCGSkillPreviewReactionInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_GCGSkillPreviewElementReactionInfo_proto_init() }
func file_GCGSkillPreviewElementReactionInfo_proto_init() {
	if File_GCGSkillPreviewElementReactionInfo_proto != nil {
		return
	}
	file_GCGSkillPreviewReactionInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GCGSkillPreviewElementReactionInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GCGSkillPreviewElementReactionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GCGSkillPreviewElementReactionInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GCGSkillPreviewElementReactionInfo_proto_goTypes,
		DependencyIndexes: file_GCGSkillPreviewElementReactionInfo_proto_depIdxs,
		MessageInfos:      file_GCGSkillPreviewElementReactionInfo_proto_msgTypes,
	}.Build()
	File_GCGSkillPreviewElementReactionInfo_proto = out.File
	file_GCGSkillPreviewElementReactionInfo_proto_rawDesc = nil
	file_GCGSkillPreviewElementReactionInfo_proto_goTypes = nil
	file_GCGSkillPreviewElementReactionInfo_proto_depIdxs = nil
}
