// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: InfernceWordInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfernceWordInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordId         uint32 `protobuf:"varint,8,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
	IsInterpret    bool   `protobuf:"varint,15,opt,name=is_interpret,json=isInterpret,proto3" json:"is_interpret,omitempty"`
	IsSubmit       bool   `protobuf:"varint,10,opt,name=is_submit,json=isSubmit,proto3" json:"is_submit,omitempty"`
	IsAssociate    bool   `protobuf:"varint,6,opt,name=is_associate,json=isAssociate,proto3" json:"is_associate,omitempty"`
	UnlockByWordId uint32 `protobuf:"varint,5,opt,name=unlock_by_word_id,json=unlockByWordId,proto3" json:"unlock_by_word_id,omitempty"`
}

func (x *InfernceWordInfo) Reset() {
	*x = InfernceWordInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InfernceWordInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfernceWordInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfernceWordInfo) ProtoMessage() {}

func (x *InfernceWordInfo) ProtoReflect() protoreflect.Message {
	mi := &file_InfernceWordInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfernceWordInfo.ProtoReflect.Descriptor instead.
func (*InfernceWordInfo) Descriptor() ([]byte, []int) {
	return file_InfernceWordInfo_proto_rawDescGZIP(), []int{0}
}

func (x *InfernceWordInfo) GetWordId() uint32 {
	if x != nil {
		return x.WordId
	}
	return 0
}

func (x *InfernceWordInfo) GetIsInterpret() bool {
	if x != nil {
		return x.IsInterpret
	}
	return false
}

func (x *InfernceWordInfo) GetIsSubmit() bool {
	if x != nil {
		return x.IsSubmit
	}
	return false
}

func (x *InfernceWordInfo) GetIsAssociate() bool {
	if x != nil {
		return x.IsAssociate
	}
	return false
}

func (x *InfernceWordInfo) GetUnlockByWordId() uint32 {
	if x != nil {
		return x.UnlockByWordId
	}
	return 0
}

var File_InfernceWordInfo_proto protoreflect.FileDescriptor

var file_InfernceWordInfo_proto_rawDesc = []byte{
	0x0a, 0x16, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x6e, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb9, 0x01, 0x0a, 0x10, 0x49, 0x6e, 0x66, 0x65, 0x72, 0x6e, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x73, 0x5f, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65,
	0x12, 0x29, 0x0a, 0x11, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x62, 0x79, 0x5f, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x75, 0x6e, 0x6c,
	0x6f, 0x63, 0x6b, 0x42, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_InfernceWordInfo_proto_rawDescOnce sync.Once
	file_InfernceWordInfo_proto_rawDescData = file_InfernceWordInfo_proto_rawDesc
)

func file_InfernceWordInfo_proto_rawDescGZIP() []byte {
	file_InfernceWordInfo_proto_rawDescOnce.Do(func() {
		file_InfernceWordInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_InfernceWordInfo_proto_rawDescData)
	})
	return file_InfernceWordInfo_proto_rawDescData
}

var file_InfernceWordInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_InfernceWordInfo_proto_goTypes = []interface{}{
	(*InfernceWordInfo)(nil), // 0: proto.InfernceWordInfo
}
var file_InfernceWordInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_InfernceWordInfo_proto_init() }
func file_InfernceWordInfo_proto_init() {
	if File_InfernceWordInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_InfernceWordInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfernceWordInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InfernceWordInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InfernceWordInfo_proto_goTypes,
		DependencyIndexes: file_InfernceWordInfo_proto_depIdxs,
		MessageInfos:      file_InfernceWordInfo_proto_msgTypes,
	}.Build()
	File_InfernceWordInfo_proto = out.File
	file_InfernceWordInfo_proto_rawDesc = nil
	file_InfernceWordInfo_proto_goTypes = nil
	file_InfernceWordInfo_proto_depIdxs = nil
}
