// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: InstableSprayStageInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstableSprayStageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFinished   bool                     `protobuf:"varint,10,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	MaxScore     uint32                   `protobuf:"varint,3,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	StageId      uint32                   `protobuf:"varint,4,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	TeamInfoList []*InstableSprayTeamInfo `protobuf:"bytes,6,rep,name=team_info_list,json=teamInfoList,proto3" json:"team_info_list,omitempty"`
}

func (x *InstableSprayStageInfo) Reset() {
	*x = InstableSprayStageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InstableSprayStageInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstableSprayStageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstableSprayStageInfo) ProtoMessage() {}

func (x *InstableSprayStageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_InstableSprayStageInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstableSprayStageInfo.ProtoReflect.Descriptor instead.
func (*InstableSprayStageInfo) Descriptor() ([]byte, []int) {
	return file_InstableSprayStageInfo_proto_rawDescGZIP(), []int{0}
}

func (x *InstableSprayStageInfo) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *InstableSprayStageInfo) GetMaxScore() uint32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *InstableSprayStageInfo) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *InstableSprayStageInfo) GetTeamInfoList() []*InstableSprayTeamInfo {
	if x != nil {
		return x.TeamInfoList
	}
	return nil
}

var File_InstableSprayStageInfo_proto protoreflect.FileDescriptor

var file_InstableSprayStageInfo_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x72, 0x61, 0x79, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x70, 0x72, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x70, 0x72, 0x61, 0x79, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x0e, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x70, 0x72, 0x61, 0x79, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x74, 0x65,
	0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_InstableSprayStageInfo_proto_rawDescOnce sync.Once
	file_InstableSprayStageInfo_proto_rawDescData = file_InstableSprayStageInfo_proto_rawDesc
)

func file_InstableSprayStageInfo_proto_rawDescGZIP() []byte {
	file_InstableSprayStageInfo_proto_rawDescOnce.Do(func() {
		file_InstableSprayStageInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_InstableSprayStageInfo_proto_rawDescData)
	})
	return file_InstableSprayStageInfo_proto_rawDescData
}

var file_InstableSprayStageInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_InstableSprayStageInfo_proto_goTypes = []interface{}{
	(*InstableSprayStageInfo)(nil), // 0: proto.InstableSprayStageInfo
	(*InstableSprayTeamInfo)(nil),  // 1: proto.InstableSprayTeamInfo
}
var file_InstableSprayStageInfo_proto_depIdxs = []int32{
	1, // 0: proto.InstableSprayStageInfo.team_info_list:type_name -> proto.InstableSprayTeamInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_InstableSprayStageInfo_proto_init() }
func file_InstableSprayStageInfo_proto_init() {
	if File_InstableSprayStageInfo_proto != nil {
		return
	}
	file_InstableSprayTeamInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_InstableSprayStageInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstableSprayStageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InstableSprayStageInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InstableSprayStageInfo_proto_goTypes,
		DependencyIndexes: file_InstableSprayStageInfo_proto_depIdxs,
		MessageInfos:      file_InstableSprayStageInfo_proto_msgTypes,
	}.Build()
	File_InstableSprayStageInfo_proto = out.File
	file_InstableSprayStageInfo_proto_rawDesc = nil
	file_InstableSprayStageInfo_proto_goTypes = nil
	file_InstableSprayStageInfo_proto_depIdxs = nil
}
