// Sorapointa - A server software re-implementation for a certain anime game, and avoid sorapointa.
// Copyright (C) 2022  Sorapointa Team
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: ToTheMoonObstaclesModifyNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 6199
// EnetChannelId: 0
// EnetIsReliable: true
// IsAllowClient: true
type ToTheMoonObstaclesModifyNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddObstacles      []*ToTheMoonObstacleInfo `protobuf:"bytes,4,rep,name=add_obstacles,json=addObstacles,proto3" json:"add_obstacles,omitempty"`
	RemoveObstacleIds []int32                  `protobuf:"varint,13,rep,packed,name=remove_obstacle_ids,json=removeObstacleIds,proto3" json:"remove_obstacle_ids,omitempty"`
	SceneId           uint32                   `protobuf:"varint,15,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	UseEdge           bool                     `protobuf:"varint,1,opt,name=use_edge,json=useEdge,proto3" json:"use_edge,omitempty"`
}

func (x *ToTheMoonObstaclesModifyNotify) Reset() {
	*x = ToTheMoonObstaclesModifyNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ToTheMoonObstaclesModifyNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToTheMoonObstaclesModifyNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToTheMoonObstaclesModifyNotify) ProtoMessage() {}

func (x *ToTheMoonObstaclesModifyNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ToTheMoonObstaclesModifyNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToTheMoonObstaclesModifyNotify.ProtoReflect.Descriptor instead.
func (*ToTheMoonObstaclesModifyNotify) Descriptor() ([]byte, []int) {
	return file_ToTheMoonObstaclesModifyNotify_proto_rawDescGZIP(), []int{0}
}

func (x *ToTheMoonObstaclesModifyNotify) GetAddObstacles() []*ToTheMoonObstacleInfo {
	if x != nil {
		return x.AddObstacles
	}
	return nil
}

func (x *ToTheMoonObstaclesModifyNotify) GetRemoveObstacleIds() []int32 {
	if x != nil {
		return x.RemoveObstacleIds
	}
	return nil
}

func (x *ToTheMoonObstaclesModifyNotify) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *ToTheMoonObstaclesModifyNotify) GetUseEdge() bool {
	if x != nil {
		return x.UseEdge
	}
	return false
}

var File_ToTheMoonObstaclesModifyNotify_proto protoreflect.FileDescriptor

var file_ToTheMoonObstaclesModifyNotify_proto_rawDesc = []byte{
	0x0a, 0x24, 0x54, 0x6f, 0x54, 0x68, 0x65, 0x4d, 0x6f, 0x6f, 0x6e, 0x4f, 0x62, 0x73, 0x74, 0x61,
	0x63, 0x6c, 0x65, 0x73, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x54,
	0x6f, 0x54, 0x68, 0x65, 0x4d, 0x6f, 0x6f, 0x6e, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x1e, 0x54,
	0x6f, 0x54, 0x68, 0x65, 0x4d, 0x6f, 0x6f, 0x6e, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65,
	0x73, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x41, 0x0a,
	0x0d, 0x61, 0x64, 0x64, 0x5f, 0x6f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x6f, 0x54,
	0x68, 0x65, 0x4d, 0x6f, 0x6f, 0x6e, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6f, 0x62, 0x73, 0x74, 0x61,
	0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x05, 0x52, 0x11, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x5f, 0x65, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75,
	0x73, 0x65, 0x45, 0x64, 0x67, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ToTheMoonObstaclesModifyNotify_proto_rawDescOnce sync.Once
	file_ToTheMoonObstaclesModifyNotify_proto_rawDescData = file_ToTheMoonObstaclesModifyNotify_proto_rawDesc
)

func file_ToTheMoonObstaclesModifyNotify_proto_rawDescGZIP() []byte {
	file_ToTheMoonObstaclesModifyNotify_proto_rawDescOnce.Do(func() {
		file_ToTheMoonObstaclesModifyNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ToTheMoonObstaclesModifyNotify_proto_rawDescData)
	})
	return file_ToTheMoonObstaclesModifyNotify_proto_rawDescData
}

var file_ToTheMoonObstaclesModifyNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ToTheMoonObstaclesModifyNotify_proto_goTypes = []interface{}{
	(*ToTheMoonObstaclesModifyNotify)(nil), // 0: proto.ToTheMoonObstaclesModifyNotify
	(*ToTheMoonObstacleInfo)(nil),          // 1: proto.ToTheMoonObstacleInfo
}
var file_ToTheMoonObstaclesModifyNotify_proto_depIdxs = []int32{
	1, // 0: proto.ToTheMoonObstaclesModifyNotify.add_obstacles:type_name -> proto.ToTheMoonObstacleInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ToTheMoonObstaclesModifyNotify_proto_init() }
func file_ToTheMoonObstaclesModifyNotify_proto_init() {
	if File_ToTheMoonObstaclesModifyNotify_proto != nil {
		return
	}
	file_ToTheMoonObstacleInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ToTheMoonObstaclesModifyNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToTheMoonObstaclesModifyNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ToTheMoonObstaclesModifyNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ToTheMoonObstaclesModifyNotify_proto_goTypes,
		DependencyIndexes: file_ToTheMoonObstaclesModifyNotify_proto_depIdxs,
		MessageInfos:      file_ToTheMoonObstaclesModifyNotify_proto_msgTypes,
	}.Build()
	File_ToTheMoonObstaclesModifyNotify_proto = out.File
	file_ToTheMoonObstaclesModifyNotify_proto_rawDesc = nil
	file_ToTheMoonObstaclesModifyNotify_proto_goTypes = nil
	file_ToTheMoonObstaclesModifyNotify_proto_depIdxs = nil
}
